"""Append Sections 10-13 (EGARCH-X) to Methodology.ipynb."""
import json, os

REPO = r'c:\Users\PCUser\Documents\GitHub\master_thesis_repo'
NB   = os.path.join(REPO, 'Methodology.ipynb')

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def md(src):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': src}

def code(src):
    return {'cell_type': 'code', 'execution_count': None,
            'metadata': {}, 'outputs': [], 'source': src}

new_cells = []

# ── SECTION 10 — Spec overview (markdown only) ───────────────────────────────
new_cells.append(md(
    '## Section 10 — EGARCH(1,1)-X Specification Overview\n\n'
    '### Variance equation\n\n'
    '$$\n'
    r'\ln(\sigma^2_t) = \omega + \alpha\left[|z_{t-1}| - \mathbb{E}|z_{t-1}|\right]'
    r' + \xi \cdot z_{t-1} + \beta \cdot \ln(\sigma^2_{t-1})'
    r' + \gamma_1 \cdot \text{Tone}_{m,t-1} + \gamma_2 \cdot \text{Volume}_{m,t-1}'
    '\n$$\n\n'
    r'where $z_t = \varepsilon_t / \sigma_t$ is the standardised residual and '
    r'$\mathbb{E}|z| = \sqrt{2/\pi}$ for the Normal baseline (distribution-corrected for '
    r'Student-$t$ and GED).'
    '\n\n'
    '### Why EGARCH for signed sentiment\n\n'
    'Standard GARCH constrains $\\sigma^2_t > 0$ via positivity restrictions on $\\omega, \\alpha, \\beta$, '
    'which forces any exogenous regressor entering the variance equation to be non-negative '
    '(e.g. squared or absolute sentiment). '
    'EGARCH models **log-variance** and has no positivity constraint, so standardised '
    '*signed* tone — which ranges over the real line — can enter $\\ln(\\sigma^2_t)$ directly '
    'without transformation (methodology §3.4.3). '
    'A negative coefficient $\\gamma_1 < 0$ means negative tone increases forecasted variance, '
    'the theoretically expected direction.\n\n'
    '### Empirical caveat: leverage effect\n\n'
    'EDA §5b (Engle-Ng sign bias test) found **no significant asymmetric volatility response** '
    'for any of the four metals (joint $p > 0.47$). This means the leverage parameter $\\xi$ '
    'may not be significant in-sample — the data do not require asymmetric treatment of positive '
    'vs negative *return* shocks. The EGARCH specification is retained because:\n\n'
    '1. EDA §5b tests return-sign asymmetry, not news-sentiment asymmetry — these are distinct channels.\n'
    '2. EGARCH is the natural model for signed regressors regardless of $\\xi$.\n'
    '3. $\\gamma_1$ and $\\gamma_2$ are the **primary parameters of interest**; '
    '$\\xi$ is reported for completeness but its insignificance does not invalidate the exercise.\n\n'
    '### Implementation path\n\n'
    'The `arch` library routes exogenous variables to the **mean** equation via the `x` argument; '
    'it does not expose variance-equation exogenous regressors for EGARCH through the public API. '
    'We therefore use a **two-step approach** (standard in the literature, e.g. Engle 2002):\n\n'
    '1. Fit EGARCH(1,1,1) without sentiment on the training sample — recovers $\\omega, \\alpha, \\xi, \\beta$.\n'
    '2. Regress the fitted $\\ln(\\hat{\\sigma}^2_t)$ series on the lagged sentiment regressors '
    'via OLS with Newey-West (HAC) standard errors — recovers $\\gamma_1, \\gamma_2$.\n\n'
    'For out-of-sample forecasting, the EGARCH one-step-ahead log-variance forecast is adjusted '
    'by the fixed training-sample $\\hat{\\gamma}_1, \\hat{\\gamma}_2$ before exponentiating. '
    'The EGARCH base AIC/BIC is reported for comparisons; the marginal sentiment contribution '
    'is evaluated through coefficient significance and residual diagnostics.'
))

# ── SECTION 11 — EGARCH-X, BIC lag ───────────────────────────────────────────
new_cells.append(md(
    '## Section 11 — EGARCH(1,1)-X Estimation: Primary (BIC) Lag\n\n'
    'BIC-optimal sentiment lags from EDA §8c: Nd=8, Pr=6, Dy=9, Tb=4. '
    'These emerge from a grid search (OLS: $r^2_t \\sim r^2_{t-1} + \\text{tone}_{t-L}$, $L=1..10$) '
    'minimising BIC per metal. The long lags (4–9 days) suggest the OTC price-discovery process '
    'absorbs news slowly — consistent with the illiquidity and forward-fill findings in EDA §2.\n\n'
    'Two regressors per metal:\n'
    '- $\\gamma_1$: `tone_mean_std_lag{L}_{metal}` — signed news direction\n'
    '- $\\gamma_2$: `log_volume_std_lag{L}_{metal}` — news-flow intensity\n\n'
    'These columns were constructed in Section 4 and are already in `df_sent`.'
))

new_cells.append(code(
    'import pickle\n'
    'import statsmodels.api as sm\n'
    'from arch import arch_model\n'
    '\n'
    '# Two-step EGARCH-X: Step 1 = base EGARCH, Step 2 = HAC aux regression\n'
    'egarchx_results_bic  = {}   # {metal: dict with fitted EGARCH res + gamma coefficients}\n'
    'egarch11_base_bic    = {}   # {metal: ARCHModelResult}  base EGARCH fits\n'
    '\n'
    'conv_log_bic = []   # metals needing convergence intervention\n'
    '\n'
    'train_mask = df_sent.index < SPLIT_DATE\n'
    '\n'
    'for metal in METALS:\n'
    '    lag_bic  = SENT_LAG_BIC[metal]\n'
    '    dist     = ERR_DIST[metal]\n'
    '    ret_train_100 = df_sent.loc[train_mask, f\'{metal}_logret\'].dropna() * 100\n'
    '\n'
    '    # ── Step 1: Fit base EGARCH(1,1,1) ────────────────────────────────\n'
    '    am = arch_model(ret_train_100, mean=\'Constant\', vol=\'EGARCH\',\n'
    '                    p=1, o=1, q=1, dist=dist)\n'
    '\n'
    '    conv_attempts = []\n'
    '    res = None\n'
    '\n'
    '    # Attempt 1: default BFGS\n'
    '    try:\n'
    '        res = am.fit(disp=\'off\', show_warning=False, update_freq=0)\n'
    '        if res.convergence_flag != 0:\n'
    '            conv_attempts.append(\'BFGS failed\')\n'
    '            res = None\n'
    '    except Exception as e:\n'
    '        conv_attempts.append(f\'BFGS error: {str(e)[:40]}\')\n'
    '\n'
    '    # Attempt 2: more iterations\n'
    '    if res is None:\n'
    '        try:\n'
    '            res = am.fit(disp=\'off\', show_warning=False, update_freq=0,\n'
    '                         options={\'maxiter\': 2000, \'ftol\': 1e-9})\n'
    '            if res.convergence_flag != 0:\n'
    '                conv_attempts.append(\'BFGS-2000 failed\')\n'
    '                res = None\n'
    '        except Exception as e:\n'
    '            conv_attempts.append(f\'BFGS-2000 error: {str(e)[:40]}\')\n'
    '\n'
    '    # Attempt 3: Nelder-Mead fallback\n'
    '    if res is None:\n'
    '        try:\n'
    '            res = am.fit(disp=\'off\', show_warning=False, update_freq=0,\n'
    '                         options={\'method\': \'Nelder-Mead\', \'maxiter\': 5000})\n'
    '            conv_attempts.append(\'Used Nelder-Mead\')\n'
    '        except Exception as e:\n'
    '            conv_attempts.append(f\'Nelder-Mead error: {str(e)[:40]}\')\n'
    '\n'
    '    if res is None:\n'
    '        print(f\'[{metal}] CONVERGENCE FAILED after all attempts: {conv_attempts}\')\n'
    '        egarchx_results_bic[metal] = None\n'
    '        continue\n'
    '\n'
    '    if conv_attempts:\n'
    '        print(f\'[{metal}] Convergence required intervention: {conv_attempts}\')\n'
    '        conv_log_bic.append(f\'{metal}: {conv_attempts}\')\n'
    '\n'
    '    egarch11_base_bic[metal] = res\n'
    '\n'
    '    # Extract EGARCH parameters\n'
    '    params    = res.params\n'
    '    omega_e   = params.get(\'omega\',    np.nan)\n'
    '    alpha_e   = params.get(\'alpha[1]\', np.nan)\n'
    '    xi_e      = params.get(\'gamma[1]\', np.nan)   # sign/leverage\n'
    '    beta_e    = params.get(\'beta[1]\',  np.nan)\n'
    '    shape_e   = np.nan\n'
    '    for pname in [\'nu\', \'eta\', \'lambda\']:\n'
    '        if pname in params.index:\n'
    '            shape_e = params[pname]; break\n'
    '\n'
    '    # Stationarity: |beta| < 1\n'
    '    if abs(beta_e) >= 0.999:\n'
    '        print(f\'WARNING [{metal}]: |beta_EGARCH| = {abs(beta_e):.4f} (near unit-root in log-var)\')\n'
    '\n'
    '    # ── Step 2: HAC auxiliary regression ──────────────────────────────\n'
    '    log_cond_var = np.log(res.conditional_variance)   # ln(sigma^2_{pct})\n'
    '\n'
    '    sent1_col = f\'tone_mean_std_lag{lag_bic}_{metal}\'\n'
    '    sent2_col = f\'log_volume_std_lag{lag_bic}_{metal}\'\n'
    '    sent1_train = df_sent.loc[train_mask, sent1_col]\n'
    '    sent2_train = df_sent.loc[train_mask, sent2_col]\n'
    '\n'
    '    aux = pd.DataFrame({\n'
    '        \'log_sigma2\': log_cond_var,\n'
    '        \'sent1\':      sent1_train,\n'
    '        \'sent2\':      sent2_train\n'
    '    }).dropna()\n'
    '\n'
    '    X_aux = sm.add_constant(aux[[\'sent1\', \'sent2\']])\n'
    '    ols   = sm.OLS(aux[\'log_sigma2\'], X_aux).fit(\n'
    '                cov_type=\'HAC\', cov_kwds={\'maxlags\': 5, \'use_correction\': True})\n'
    '\n'
    '    gamma1    = ols.params[\'sent1\']\n'
    '    gamma2    = ols.params[\'sent2\']\n'
    '    gamma1_t  = ols.tvalues[\'sent1\']\n'
    '    gamma1_p  = ols.pvalues[\'sent1\']\n'
    '    gamma2_t  = ols.tvalues[\'sent2\']\n'
    '    gamma2_p  = ols.pvalues[\'sent2\']\n'
    '\n'
    '    # Joint Wald test H0: gamma1 = gamma2 = 0 (chi-squared, HAC)\n'
    '    r_mat = np.array([[0, 1, 0], [0, 0, 1]])\n'
    '    wald      = ols.wald_test(r_mat, use_f=False, scalar=True)\n'
    '    wald_stat = float(wald.statistic)\n'
    '    wald_p    = float(wald.pvalue)\n'
    '\n'
    '    # Flag implausibly large coefficients\n'
    '    if abs(gamma1) > 5 or abs(gamma2) > 5:\n'
    '        print(f\'WARNING [{metal}]: large auxiliary gamma — inspect regressor outliers\')\n'
    '        print(f\'  gamma1={gamma1:.4f}, gamma2={gamma2:.4f}\')\n'
    '        print(f\'  sent1 stats: mean={sent1_train.mean():.3f}, std={sent1_train.std():.3f}, \'\n'
    '              f\'max={sent1_train.max():.3f}\')\n'
    '        print(f\'  sent2 stats: mean={sent2_train.mean():.3f}, std={sent2_train.std():.3f}, \'\n'
    '              f\'max={sent2_train.max():.3f}\')\n'
    '\n'
    '    # Store everything\n'
    '    result_dict = {\n'
    '        \'metal\':       metal,\n'
    '        \'lag\':         lag_bic,\n'
    '        \'arch_res\':    res,\n'
    '        \'ols_aux\':     ols,\n'
    '        \'omega\':       omega_e,\n'
    '        \'alpha\':       alpha_e,\n'
    '        \'xi\':          xi_e,\n'
    '        \'beta\':        beta_e,\n'
    '        \'shape\':       shape_e,\n'
    '        \'loglik\':      res.loglikelihood,\n'
    '        \'aic\':         res.aic,\n'
    '        \'bic\':         res.bic,\n'
    '        \'gamma1\':      gamma1,\n'
    '        \'gamma2\':      gamma2,\n'
    '        \'gamma1_t\':    gamma1_t,\n'
    '        \'gamma1_p\':    gamma1_p,\n'
    '        \'gamma2_t\':    gamma2_t,\n'
    '        \'gamma2_p\':    gamma2_p,\n'
    '        \'wald_stat\':   wald_stat,\n'
    '        \'wald_p\':      wald_p,\n'
    '        \'conv_log\':    conv_attempts,\n'
    '    }\n'
    '    egarchx_results_bic[metal] = result_dict\n'
    '\n'
    '    pkl_path = f\'outputs/egarchx_bic_{metal}.pkl\'\n'
    '    with open(pkl_path, \'wb\') as fh:\n'
    '        pickle.dump(result_dict, fh)\n'
    '\n'
    '    print(f\'[{metal}] lag={lag_bic}: gamma1(tone)={gamma1:.4f} (t={gamma1_t:.2f}, \'\n'
    '          f\'p={gamma1_p:.3f}), gamma2(vol)={gamma2:.4f} (t={gamma2_t:.2f}, \'\n'
    '          f\'p={gamma2_p:.3f}), Wald-p={wald_p:.4f}\')\n'
    '\n'
    'print(\'\\nSection 11 complete.\')\n'
    'if conv_log_bic:\n'
    '    print(\'Convergence interventions:\')\n'
    '    for entry in conv_log_bic:\n'
    '        print(f\'  {entry}\')'
))

new_cells.append(code(
    '# ── Full parameter table for BIC-lag EGARCH-X fits ────────────────────\n'
    'def sig_stars(p):\n'
    '    if p < 0.01:  return \'***\'\n'
    '    if p < 0.05:  return \'**\'\n'
    '    if p < 0.10:  return \'*\'\n'
    '    return \'\'\n'
    '\n'
    'print("EGARCH(1,1)-X Parameter Table — BIC lag")\n'
    'print("=" * 100)\n'
    'hdr = (f"  {\'Metal\':<6} {\'Lag\':>4} {\'omega\':>10} {\'alpha\':>8} {\'xi\':>8} "\n'
    '       f"{\'beta\':>8} {\'shape\':>7} {\'gamma1\':>8} {\'gamma1_p\':>9} "\n'
    '       f"{\'gamma2\':>8} {\'gamma2_p\':>9} {\'Wald-p\':>8} {\'LogLik\':>9} {\'AIC\':>9} {\'BIC\':>9}")\n'
    'print(hdr)\n'
    'print("  " + "-" * (len(hdr)-2))\n'
    'for metal in METALS:\n'
    '    r = egarchx_results_bic.get(metal)\n'
    '    if r is None:\n'
    '        print(f"  {metal:<6} CONVERGENCE FAILED")\n'
    '        continue\n'
    '    print(\n'
    '        f"  {metal:<6} {r[\'lag\']:>4} {r[\'omega\']:>10.5f} {r[\'alpha\']:>8.5f} "\n'
    '        f"{r[\'xi\']:>8.5f} {r[\'beta\']:>8.5f} {r[\'shape\']:>7.3f} "\n'
    '        f"{r[\'gamma1\']:>8.4f}{sig_stars(r[\'gamma1_p\']):3s} "\n'
    '        f"{r[\'gamma1_p\']:>9.4f} {r[\'gamma2\']:>8.4f}{sig_stars(r[\'gamma2_p\']):3s} "\n'
    '        f"{r[\'gamma2_p\']:>9.4f} {r[\'wald_p\']:>8.4f} "\n'
    '        f"{r[\'loglik\']:>9.2f} {r[\'aic\']:>9.2f} {r[\'bic\']:>9.2f}"\n'
    '    )\n'
    'print("\\nNote: stars on gamma1/gamma2 from HAC-robust t-tests. "\n'
    '      "Wald p: joint H0: gamma1=gamma2=0.")'
))

# ── SECTION 12 — EGARCH-X, lag 1 robustness ──────────────────────────────────
new_cells.append(md(
    '## Section 12 — EGARCH(1,1)-X Estimation: Robustness Lag (L=1)\n\n'
    'Granger causality tests at lag 1 (EDA §8) found significant predictability for '
    'Nd (log_volume → r², p=0.008), Pr (tone → r², p=0.039), and Dy (log_volume → r², p=0.002). '
    'Tb showed no significance at any lag. '
    'This motivates a robustness specification with `SENT_LAG_ROBUST = 1` across all metals, '
    'which is both economically intuitive (yesterday\'s news affects today\'s volatility) '
    'and statistically justified by the Granger results.\n\n'
    'The BIC lags (4–9 days) from EDA §8c may reflect fitting noise in the OLS grid search '
    'rather than a true informational delay, particularly for Nd (lag=8) and Dy (lag=9).'
))

new_cells.append(code(
    '# Section 12 mirrors Section 11 exactly, using SENT_LAG_ROBUST = 1\n'
    '# Granger at lag 1: Nd->log_volume p=0.008, Pr->tone p=0.039,\n'
    '#   Dy->log_volume p=0.002, Tb: none — EDA §8\n'
    '\n'
    'egarchx_results_l1 = {}   # {metal: result_dict}\n'
    'egarch11_base_l1   = {}   # {metal: ARCHModelResult}\n'
    'conv_log_l1 = []\n'
    '\n'
    'for metal in METALS:\n'
    '    lag_rob  = SENT_LAG_ROBUST   # = 1\n'
    '    dist     = ERR_DIST[metal]\n'
    '    ret_train_100 = df_sent.loc[train_mask, f\'{metal}_logret\'].dropna() * 100\n'
    '\n'
    '    # Reuse base EGARCH fit from Section 11 if it converged\n'
    '    if metal in egarch11_base_bic:\n'
    '        res = egarch11_base_bic[metal]   # same EGARCH base — only sentiment regressors differ\n'
    '        base_reused = True\n'
    '    else:\n'
    '        base_reused = False\n'
    '        am = arch_model(ret_train_100, mean=\'Constant\', vol=\'EGARCH\',\n'
    '                        p=1, o=1, q=1, dist=dist)\n'
    '        conv_attempts = []\n'
    '        res = None\n'
    '        for opt in [{}, {\'maxiter\': 2000, \'ftol\': 1e-9}]:\n'
    '            try:\n'
    '                res = am.fit(disp=\'off\', show_warning=False, update_freq=0,\n'
    '                             options=opt if opt else None)\n'
    '                if res.convergence_flag == 0:\n'
    '                    break\n'
    '                conv_attempts.append(f\'attempt with {opt} failed\')\n'
    '                res = None\n'
    '            except Exception as e:\n'
    '                conv_attempts.append(str(e)[:50])\n'
    '        if res is None:\n'
    '            print(f\'[{metal}] L1 base EGARCH convergence failed\')\n'
    '            egarchx_results_l1[metal] = None\n'
    '            continue\n'
    '        if conv_attempts:\n'
    '            conv_log_l1.append(f\'{metal}: {conv_attempts}\')\n'
    '\n'
    '    egarch11_base_l1[metal] = res\n'
    '\n'
    '    # Extract base EGARCH parameters\n'
    '    params   = res.params\n'
    '    omega_e  = params.get(\'omega\',    np.nan)\n'
    '    alpha_e  = params.get(\'alpha[1]\', np.nan)\n'
    '    xi_e     = params.get(\'gamma[1]\', np.nan)\n'
    '    beta_e   = params.get(\'beta[1]\',  np.nan)\n'
    '    shape_e  = np.nan\n'
    '    for pname in [\'nu\', \'eta\', \'lambda\']:\n'
    '        if pname in params.index:\n'
    '            shape_e = params[pname]; break\n'
    '\n'
    '    # HAC auxiliary regression with lag-1 sentiment\n'
    '    log_cond_var = np.log(res.conditional_variance)\n'
    '    sent1_col = f\'tone_mean_std_lag1_{metal}\'\n'
    '    sent2_col = f\'log_volume_std_lag1_{metal}\'\n'
    '    sent1_tr  = df_sent.loc[train_mask, sent1_col]\n'
    '    sent2_tr  = df_sent.loc[train_mask, sent2_col]\n'
    '\n'
    '    aux = pd.DataFrame({\n'
    '        \'log_sigma2\': log_cond_var,\n'
    '        \'sent1\':      sent1_tr,\n'
    '        \'sent2\':      sent2_tr\n'
    '    }).dropna()\n'
    '\n'
    '    X_aux = sm.add_constant(aux[[\'sent1\', \'sent2\']])\n'
    '    ols   = sm.OLS(aux[\'log_sigma2\'], X_aux).fit(\n'
    '                cov_type=\'HAC\', cov_kwds={\'maxlags\': 5, \'use_correction\': True})\n'
    '\n'
    '    gamma1   = ols.params[\'sent1\']\n'
    '    gamma2   = ols.params[\'sent2\']\n'
    '    gamma1_t = ols.tvalues[\'sent1\']\n'
    '    gamma1_p = ols.pvalues[\'sent1\']\n'
    '    gamma2_t = ols.tvalues[\'sent2\']\n'
    '    gamma2_p = ols.pvalues[\'sent2\']\n'
    '\n'
    '    r_mat    = np.array([[0, 1, 0], [0, 0, 1]])\n'
    '    wald     = ols.wald_test(r_mat, use_f=False, scalar=True)\n'
    '    wald_stat = float(wald.statistic)\n'
    '    wald_p   = float(wald.pvalue)\n'
    '\n'
    '    if abs(gamma1) > 5 or abs(gamma2) > 5:\n'
    '        print(f\'WARNING [{metal}] L1: large gamma (gamma1={gamma1:.4f}, gamma2={gamma2:.4f})\')\n'
    '\n'
    '    result_dict = {\n'
    '        \'metal\':       metal,\n'
    '        \'lag\':         lag_rob,\n'
    '        \'arch_res\':    res,\n'
    '        \'ols_aux\':     ols,\n'
    '        \'omega\':       omega_e,\n'
    '        \'alpha\':       alpha_e,\n'
    '        \'xi\':          xi_e,\n'
    '        \'beta\':        beta_e,\n'
    '        \'shape\':       shape_e,\n'
    '        \'loglik\':      res.loglikelihood,\n'
    '        \'aic\':         res.aic,\n'
    '        \'bic\':         res.bic,\n'
    '        \'gamma1\':      gamma1,\n'
    '        \'gamma2\':      gamma2,\n'
    '        \'gamma1_t\':    gamma1_t,\n'
    '        \'gamma1_p\':    gamma1_p,\n'
    '        \'gamma2_t\':    gamma2_t,\n'
    '        \'gamma2_p\':    gamma2_p,\n'
    '        \'wald_stat\':   wald_stat,\n'
    '        \'wald_p\':      wald_p,\n'
    '        \'conv_log\':    conv_log_l1,\n'
    '        \'base_reused\': base_reused,\n'
    '    }\n'
    '    egarchx_results_l1[metal] = result_dict\n'
    '\n'
    '    pkl_path = f\'outputs/egarchx_l1_{metal}.pkl\'\n'
    '    with open(pkl_path, \'wb\') as fh:\n'
    '        pickle.dump(result_dict, fh)\n'
    '\n'
    '    print(f\'[{metal}] L1: gamma1(tone)={gamma1:.4f} (t={gamma1_t:.2f}, p={gamma1_p:.3f}), \'\n'
    '          f\'gamma2(vol)={gamma2:.4f} (t={gamma2_t:.2f}, p={gamma2_p:.3f}), Wald-p={wald_p:.4f}\')\n'
    '\n'
    'print(\'\\nSection 12 complete.\')'
))

new_cells.append(code(
    '# ── Side-by-side comparison: BIC lag vs L=1 ───────────────────────────\n'
    '# Helps assess whether BIC lags are overfitting noise — EDA §8c\n'
    '\n'
    'comp_rows = []\n'
    'for metal in METALS:\n'
    '    rb = egarchx_results_bic.get(metal)\n'
    '    rl = egarchx_results_l1.get(metal)\n'
    '    comp_rows.append({\n'
    '        \'Metal\':        metal,\n'
    '        \'BIC_lag\':      rb[\'lag\']     if rb else np.nan,\n'
    '        \'g1_BIC\':       rb[\'gamma1\']  if rb else np.nan,\n'
    '        \'g1t_BIC\':      rb[\'gamma1_t\'] if rb else np.nan,\n'
    '        \'g1p_BIC\':      rb[\'gamma1_p\'] if rb else np.nan,\n'
    '        \'g2_BIC\':       rb[\'gamma2\']  if rb else np.nan,\n'
    '        \'g2t_BIC\':      rb[\'gamma2_t\'] if rb else np.nan,\n'
    '        \'g2p_BIC\':      rb[\'gamma2_p\'] if rb else np.nan,\n'
    '        \'AIC_BIC\':      rb[\'aic\']     if rb else np.nan,\n'
    '        \'BIC_BIC\':      rb[\'bic\']     if rb else np.nan,\n'
    '        \'g1_L1\':        rl[\'gamma1\']  if rl else np.nan,\n'
    '        \'g1t_L1\':       rl[\'gamma1_t\'] if rl else np.nan,\n'
    '        \'g1p_L1\':       rl[\'gamma1_p\'] if rl else np.nan,\n'
    '        \'g2_L1\':        rl[\'gamma2\']  if rl else np.nan,\n'
    '        \'g2t_L1\':       rl[\'gamma2_t\'] if rl else np.nan,\n'
    '        \'g2p_L1\':       rl[\'gamma2_p\'] if rl else np.nan,\n'
    '        \'AIC_L1\':       rl[\'aic\']     if rl else np.nan,\n'
    '        \'BIC_L1\':       rl[\'bic\']     if rl else np.nan,\n'
    '    })\n'
    '\n'
    'comp_df = pd.DataFrame(comp_rows)\n'
    '\n'
    'print("Side-by-side: gamma1 (tone) and gamma2 (volume) — BIC lag vs L=1")\n'
    'print("=" * 90)\n'
    'print(f"  {\'Metal\':<6} {\'Lag\':>4}  "\n'
    '      f"{\'g1(BIC)\':>9} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'g1(L1)\':>9} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'g2(BIC)\':>9} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'g2(L1)\':>9} {\'t\':>6} {\'p\':>6}")\n'
    'print("  " + "-" * 88)\n'
    'for _, row in comp_df.iterrows():\n'
    '    print(\n'
    '        f"  {row[\'Metal\']:<6} {row[\'BIC_lag\']:>4.0f}  "\n'
    '        f"{row[\'g1_BIC\']:>9.4f} {row[\'g1t_BIC\']:>6.2f} {row[\'g1p_BIC\']:>6.3f}  "\n'
    '        f"{row[\'g1_L1\']:>9.4f} {row[\'g1t_L1\']:>6.2f} {row[\'g1p_L1\']:>6.3f}  "\n'
    '        f"{row[\'g2_BIC\']:>9.4f} {row[\'g2t_BIC\']:>6.2f} {row[\'g2p_BIC\']:>6.3f}  "\n'
    '        f"{row[\'g2_L1\']:>9.4f} {row[\'g2t_L1\']:>6.2f} {row[\'g2p_L1\']:>6.3f}"\n'
    '    )\n'
    '\n'
    'print("\\nAIC/BIC: EGARCH base is the same for both lag specs (only aux regression differs)")\n'
    'print(f"  {\'Metal\':<6} {\'AIC_BIC_lag\':>12} {\'BIC_BIC_lag\':>12}")\n'
    'for _, row in comp_df.iterrows():\n'
    '    print(f"  {row[\'Metal\']:<6} {row[\'AIC_BIC\']:>12.2f} {row[\'BIC_BIC\']:>12.2f}")'
))

new_cells.append(md(
    '### Section 12 — BIC lag vs L=1 commentary\n\n'
    'The two lag specifications use the **same** EGARCH base model (Section 11 base is reused '
    'for Section 12 when it converged), so their AIC/BIC values are identical — only the '
    'auxiliary regression changes. The comparison is therefore purely about coefficient sign, '
    'magnitude, and HAC significance.\n\n'
    '**Interpretation guide:**\n\n'
    '- If both lag specs agree on sign and significance → the sentiment signal is robust to lag choice.\n'
    '- If only the BIC lag is significant → the OLS grid search found a real delay, or overfit noise. '
    '  Check whether the BIC lag is economically plausible (a 9-day lag for Dy is unusual).\n'
    '- If only L=1 is significant → the Granger result at lag 1 (EDA §8) is the stronger signal. '
    '  This is the lag-1 robustness specification that directly motivates the choice of `SENT_LAG_ROBUST`.\n'
    '- If neither is significant → sentiment does not enter the variance equation through these channels, '
    '  consistent with efficient pricing. The out-of-sample evidence (Section 13) is the final arbiter.'
))

# ── SECTION 13 — Forecasts and diagnostics ───────────────────────────────────
new_cells.append(md(
    '## Section 13 — EGARCH-X Test-Period Forecasts and In-Sample Diagnostics\n\n'
    'Three sub-sections:\n'
    '- **13a**: Expanding-window one-step-ahead variance forecasts for both lag specs\n'
    '- **13b**: In-sample Ljung-Box diagnostics on EGARCH standardised residuals\n'
    '- **13c**: Readiness summary with coefficient table, AIC/BIC comparison, and narrative'
))

# 13a — Forecasts
new_cells.append(md(
    '### Section 13a — Expanding-Window Forecasts\n\n'
    'Same expanding-window scheme as Section 7 (GARCH baseline) for a clean comparison. '
    'At each test date $t$, EGARCH(1,1,1) is refitted on all data up to $t$, '
    'the one-step-ahead log-variance forecast is obtained, and the fixed training-sample '
    '$\\hat{\\gamma}_1, \\hat{\\gamma}_2$ are applied as an additive adjustment before '
    'exponentiating back to variance space:\n\n'
    '$$\\hat{\\sigma}^2_{t+1} = \\exp\\!\\left[\\ln(\\hat{\\sigma}^2_{t+1|t})_{\\text{EGARCH}} '
    '+ \\hat{\\gamma}_1 \\cdot \\text{Tone}_{m,t-L+1} '
    '+ \\hat{\\gamma}_2 \\cdot \\text{Vol}_{m,t-L+1}\\right] / 10^4$$\n\n'
    'The division by $10^4$ converts from percentage-return variance (EGARCH fit on returns×100) '
    'back to decimal-return variance.\n\n'
    'Budget rule: refit every step; switch to every 22 steps if any single metal exceeds '
    '15 minutes wall-clock, matching the Section 7 precedent.'
))

new_cells.append(code(
    'import time\n'
    '\n'
    '# Expanding-window EGARCH-X forecasts — BIC lag and L=1 simultaneously\n'
    '# Reuses fixed gammas from training-sample auxiliary regressions (Sections 11/12)\n'
    '\n'
    'egarchx_forecasts_bic = {}   # {metal: pd.Series}\n'
    'egarchx_forecasts_l1  = {}   # {metal: pd.Series}\n'
    '\n'
    'REFIT_FREQ_EG = 1\n'
    'test_dates    = df_sent.index[df_sent.index >= SPLIT_DATE]\n'
    'all_dates     = df_sent.index\n'
    '\n'
    'total_start_eg = time.time()\n'
    '\n'
    'for metal in METALS:\n'
    '    ret_full_100 = df_sent[f\'{metal}_logret\'].dropna() * 100\n'
    '    dist         = ERR_DIST[metal]\n'
    '\n'
    '    rb = egarchx_results_bic.get(metal)\n'
    '    rl = egarchx_results_l1.get(metal)\n'
    '    if rb is None and rl is None:\n'
    '        print(f\'[{metal}] No convergent in-sample fit — skipping forecasts\')\n'
    '        continue\n'
    '\n'
    '    # Fixed gammas from training-sample auxiliary regressions\n'
    '    g1_bic = rb[\'gamma1\'] if rb else 0.0\n'
    '    g2_bic = rb[\'gamma2\'] if rb else 0.0\n'
    '    lag_bic = SENT_LAG_BIC[metal]\n'
    '    s1_bic_col = f\'tone_mean_std_lag{lag_bic}_{metal}\'\n'
    '    s2_bic_col = f\'log_volume_std_lag{lag_bic}_{metal}\'\n'
    '\n'
    '    g1_l1 = rl[\'gamma1\'] if rl else 0.0\n'
    '    g2_l1 = rl[\'gamma2\'] if rl else 0.0\n'
    '    s1_l1_col = f\'tone_mean_std_lag1_{metal}\'\n'
    '    s2_l1_col = f\'log_volume_std_lag1_{metal}\'\n'
    '\n'
    '    forecasts_bic = []\n'
    '    forecasts_l1  = []\n'
    '    step_count_eg = 0\n'
    '    metal_start   = time.time()\n'
    '    res_eg        = rb[\'arch_res\'] if rb else rl[\'arch_res\']   # initial params for warm start\n'
    '\n'
    '    for t_date in test_dates:\n'
    '        t_pos      = all_dates.get_loc(t_date)\n'
    '        ret_window = ret_full_100.iloc[:t_pos]\n'
    '\n'
    '        var_bic = np.nan\n'
    '        var_l1  = np.nan\n'
    '\n'
    '        try:\n'
    '            am_eg = arch_model(ret_window, mean=\'Constant\', vol=\'EGARCH\',\n'
    '                               p=1, o=1, q=1, dist=dist)\n'
    '            if step_count_eg % REFIT_FREQ_EG == 0:\n'
    '                res_eg = am_eg.fit(disp=\'off\', show_warning=False, update_freq=0,\n'
    '                                   starting_values=res_eg.params.values)\n'
    '                if res_eg.convergence_flag != 0:\n'
    '                    # Retry without warm start\n'
    '                    res_eg = am_eg.fit(disp=\'off\', show_warning=False, update_freq=0)\n'
    '\n'
    '            fcast_eg = res_eg.forecast(horizon=1, reindex=False)\n'
    '            log_var_base = np.log(max(fcast_eg.variance.iloc[-1, 0], 1e-12))\n'
    '\n'
    '            # Sentiment values at this test date (pre-lagged columns)\n'
    '            s1_bic_val = df_sent.loc[t_date, s1_bic_col] if s1_bic_col in df_sent.columns else 0.0\n'
    '            s2_bic_val = df_sent.loc[t_date, s2_bic_col] if s2_bic_col in df_sent.columns else 0.0\n'
    '            s1_l1_val  = df_sent.loc[t_date, s1_l1_col]  if s1_l1_col  in df_sent.columns else 0.0\n'
    '            s2_l1_val  = df_sent.loc[t_date, s2_l1_col]  if s2_l1_col  in df_sent.columns else 0.0\n'
    '\n'
    '            # Handle NaN sentiment\n'
    '            s1_bic_val = 0.0 if pd.isna(s1_bic_val) else float(s1_bic_val)\n'
    '            s2_bic_val = 0.0 if pd.isna(s2_bic_val) else float(s2_bic_val)\n'
    '            s1_l1_val  = 0.0 if pd.isna(s1_l1_val)  else float(s1_l1_val)\n'
    '            s2_l1_val  = 0.0 if pd.isna(s2_l1_val)  else float(s2_l1_val)\n'
    '\n'
    '            var_bic = np.exp(log_var_base + g1_bic * s1_bic_val + g2_bic * s2_bic_val) / 1e4\n'
    '            var_l1  = np.exp(log_var_base + g1_l1  * s1_l1_val  + g2_l1  * s2_l1_val)  / 1e4\n'
    '\n'
    '        except Exception:\n'
    '            pass\n'
    '\n'
    '        forecasts_bic.append((t_date, var_bic))\n'
    '        forecasts_l1.append((t_date, var_l1))\n'
    '        step_count_eg += 1\n'
    '\n'
    '        # Budget check\n'
    '        if REFIT_FREQ_EG == 1 and (time.time() - metal_start) > 900 and step_count_eg < 50:\n'
    '            REFIT_FREQ_EG = 22\n'
    '            print(f\'[{metal}] EGARCH slow — switching to 22-step refit\')\n'
    '\n'
    '    fc_bic = pd.Series({d: v for d, v in forecasts_bic}, name=\'forecast_var\')\n'
    '    fc_l1  = pd.Series({d: v for d, v in forecasts_l1},  name=\'forecast_var\')\n'
    '    egarchx_forecasts_bic[metal] = fc_bic\n'
    '    egarchx_forecasts_l1[metal]  = fc_l1\n'
    '\n'
    '    with open(f\'outputs/forecasts_egarchx_bic_{metal}.pkl\', \'wb\') as fh:\n'
    '        pickle.dump(fc_bic, fh)\n'
    '    with open(f\'outputs/forecasts_egarchx_l1_{metal}.pkl\', \'wb\') as fh:\n'
    '        pickle.dump(fc_l1, fh)\n'
    '\n'
    '    elapsed = time.time() - metal_start\n'
    '    print(f\'[{metal}] EGARCH-X forecasts done — {len(fc_bic)} steps, {elapsed:.1f}s\')\n'
    '\n'
    '    if (time.time() - total_start_eg) > 1800:\n'
    '        REFIT_FREQ_EG = 22\n'
    '        print(\'Budget exceeded — remaining metals use 22-step refit\')\n'
    '\n'
    'print(f\'\\nEGARCH-X forecasts complete. Refit frequency: every {REFIT_FREQ_EG} step(s).\')'
))

# 13b — Diagnostics
new_cells.append(md(
    '### Section 13b — In-Sample Diagnostics on EGARCH Base Residuals\n\n'
    'Ljung-Box tests on standardised residuals and squared standardised residuals from the '
    'EGARCH(1,1,1) base fit (BIC lag, training sample). '
    'Compared against the Section 8 GARCH(1,1) baseline to assess whether the EGARCH '
    'specification better whitens the residuals.'
))

new_cells.append(code(
    '# In-sample Ljung-Box diagnostics — EGARCH base (BIC lag fits)\n'
    '# ARCH-LM p~0 for all metals (EDA §5) → EGARCH should absorb ARCH effects\n'
    'from statsmodels.stats.diagnostic import acorr_ljungbox\n'
    '\n'
    'eg_diag_rows = []\n'
    '\n'
    'for metal in METALS:\n'
    '    rb = egarchx_results_bic.get(metal)\n'
    '    if rb is None:\n'
    '        print(f\'[{metal}] No EGARCH fit — skipping diagnostics\')\n'
    '        continue\n'
    '    res  = rb[\'arch_res\']\n'
    '    zhat = res.std_resid.dropna()\n'
    '\n'
    '    for lag in [5, 10, 20]:\n'
    '        lb_z  = acorr_ljungbox(zhat,      lags=[lag], return_df=True)\n'
    '        lb_z2 = acorr_ljungbox(zhat ** 2, lags=[lag], return_df=True)\n'
    '        eg_diag_rows.append({\n'
    '            \'Metal\': metal, \'Test\': \'LB-z\',  \'Lag\': lag,\n'
    '            \'EGARCH_Stat\': lb_z[\'lb_stat\'].iloc[0],\n'
    '            \'EGARCH_p\':    lb_z[\'lb_pvalue\'].iloc[0]\n'
    '        })\n'
    '        eg_diag_rows.append({\n'
    '            \'Metal\': metal, \'Test\': \'LB-z^2\', \'Lag\': lag,\n'
    '            \'EGARCH_Stat\': lb_z2[\'lb_stat\'].iloc[0],\n'
    '            \'EGARCH_p\':    lb_z2[\'lb_pvalue\'].iloc[0]\n'
    '        })\n'
    '\n'
    'eg_diag_df = pd.DataFrame(eg_diag_rows)\n'
    '\n'
    '# Merge with Section 8 GARCH(1,1) diagnostics for comparison\n'
    'diag_compare = eg_diag_df.merge(\n'
    '    diag_df.rename(columns={\'Stat\': \'GARCH11_Stat\', \'p-value\': \'GARCH11_p\'}),\n'
    '    on=[\'Metal\', \'Test\', \'Lag\'], how=\'left\'\n'
    ')\n'
    '\n'
    'print("Ljung-Box diagnostics: EGARCH(1,1,1) vs GARCH(1,1) — training sample")\n'
    'print("=" * 80)\n'
    'print(diag_compare.to_string(index=False, float_format=\'{:.4f}\'.format))\n'
    'print("\\nNote: smaller p-values indicate remaining autocorrelation.")'
))

# 13c — Readiness summary
new_cells.append(md(
    '### Section 13c — Readiness Summary: EGARCH-X\n\n'
    'Confirmation of saved artifacts, full coefficient table with significance stars, '
    'AIC/BIC comparison, and a first-pass narrative on which metals show sentiment promise.'
))

new_cells.append(code(
    'import glob\n'
    '\n'
    'print("=" * 70)\n'
    'print("READINESS SUMMARY — Section 13 (EGARCH-X)")\n'
    'print("=" * 70)\n'
    '\n'
    '# ── 1. Artifacts ─────────────────────────────────────────────────────\n'
    'print("\\n[1] New artifacts under outputs/")\n'
    'for fpath in sorted(glob.glob("outputs/egarch*") + glob.glob("outputs/forecasts_egarch*")):\n'
    '    size_kb = os.path.getsize(fpath) / 1024\n'
    '    print(f"    {os.path.basename(fpath):<50s} {size_kb:6.1f} KB")\n'
    '\n'
    '# ── 2. Coefficient table: gamma1, gamma2, xi per metal x lag ─────────\n'
    'print("\\n[2] Sentiment coefficient table (HAC t-stats and significance)")\n'
    'print(f"  {\'Metal\':<6} {\'Spec\':>10}  {\'g1(tone)\':>10} {\'t\':>7} {\'p\':>6} "\n'
    '      f"{\'g2(vol)\':>10} {\'t\':>7} {\'p\':>6}  "\n'
    '      f"{\'xi(lev)\':>10} {\'Wald-p\':>8}")\n'
    'print("  " + "-" * 80)\n'
    'for metal in METALS:\n'
    '    for label, rdict in [(f\'BIC(L={SENT_LAG_BIC[metal]})\', egarchx_results_bic.get(metal)),\n'
    '                          (\'L=1\', egarchx_results_l1.get(metal))]:\n'
    '        if rdict is None:\n'
    '            print(f"  {metal:<6} {label:>10}  (no converged fit)")\n'
    '            continue\n'
    '        stars1 = sig_stars(rdict[\'gamma1_p\'])\n'
    '        stars2 = sig_stars(rdict[\'gamma2_p\'])\n'
    '        print(\n'
    '            f"  {metal:<6} {label:>10}  "\n'
    '            f"{rdict[\'gamma1\']:>10.4f}{stars1:<3s} {rdict[\'gamma1_t\']:>7.2f} {rdict[\'gamma1_p\']:>6.3f} "\n'
    '            f"{rdict[\'gamma2\']:>10.4f}{stars2:<3s} {rdict[\'gamma2_t\']:>7.2f} {rdict[\'gamma2_p\']:>6.3f}  "\n'
    '            f"{rdict[\'xi\']:>10.4f} {rdict[\'wald_p\']:>8.4f}"\n'
    '        )\n'
    '    print()\n'
    '\n'
    '# ── 3. AIC/BIC comparison: GARCH(1,1) vs EGARCH base ─────────────────\n'
    'print("[3] AIC/BIC: GARCH(1,1) baseline vs EGARCH(1,1,1) base")\n'
    'print(f"  {\'Metal\':<6} {\'GARCH11_AIC\':>12} {\'GARCH11_BIC\':>12} "\n'
    '      f"{\'EGARCH_AIC\':>12} {\'EGARCH_BIC\':>12} {\'ΔAIC\':>8} {\'ΔBIC\':>8}")\n'
    'print("  " + "-" * 70)\n'
    'for metal in METALS:\n'
    '    g11   = garch11_results.get(metal)\n'
    '    eg_r  = egarchx_results_bic.get(metal)\n'
    '    if g11 is None or eg_r is None:\n'
    '        print(f"  {metal:<6} (missing fit)")\n'
    '        continue\n'
    '    d_aic = eg_r[\'aic\'] - g11.aic\n'
    '    d_bic = eg_r[\'bic\'] - g11.bic\n'
    '    print(\n'
    '        f"  {metal:<6} {g11.aic:>12.2f} {g11.bic:>12.2f} "\n'
    '        f"{eg_r[\'aic\']:>12.2f} {eg_r[\'bic\']:>12.2f} {d_aic:>8.2f} {d_bic:>8.2f}"\n'
    '    )\n'
    'print("  (Negative ΔAIC/ΔBIC = EGARCH improves on GARCH(1,1))")\n'
    '\n'
    '# ── 4. First-pass narrative ────────────────────────────────────────────\n'
    'print("\\n[4] First-pass narrative")\n'
    'print("-" * 70)\n'
    'for metal in METALS:\n'
    '    rb = egarchx_results_bic.get(metal)\n'
    '    rl = egarchx_results_l1.get(metal)\n'
    '    if rb is None and rl is None:\n'
    '        print(f"  {metal}: no converged fit — excluded from narrative")\n'
    '        continue\n'
    '\n'
    '    signals = []\n'
    '    # BIC lag\n'
    '    if rb:\n'
    '        if rb[\'gamma1_p\'] < 0.10:\n'
    '            signals.append(f"tone sig at BIC lag {rb[\'lag\']} (p={rb[\'gamma1_p\']:.3f})")\n'
    '        if rb[\'gamma2_p\'] < 0.10:\n'
    '            signals.append(f"volume sig at BIC lag {rb[\'lag\']} (p={rb[\'gamma2_p\']:.3f})")\n'
    '        if rb[\'wald_p\'] < 0.10:\n'
    '            signals.append(f"joint Wald sig at BIC lag (p={rb[\'wald_p\']:.3f})")\n'
    '    # L=1\n'
    '    if rl:\n'
    '        if rl[\'gamma1_p\'] < 0.10:\n'
    '            signals.append(f"tone sig at L=1 (p={rl[\'gamma1_p\']:.3f})")\n'
    '        if rl[\'gamma2_p\'] < 0.10:\n'
    '            signals.append(f"volume sig at L=1 (p={rl[\'gamma2_p\']:.3f})")\n'
    '        if rl[\'wald_p\'] < 0.10:\n'
    '            signals.append(f"joint Wald sig at L=1 (p={rl[\'wald_p\']:.3f})")\n'
    '\n'
    '    # EGARCH vs GARCH AIC improvement\n'
    '    g11_res = garch11_results.get(metal)\n'
    '    if g11_res and rb:\n'
    '        d_aic = rb[\'aic\'] - g11_res.aic\n'
    '        if d_aic < -2:\n'
    '            signals.append(f"EGARCH improves AIC by {-d_aic:.1f}")\n'
    '\n'
    '    verdict = "Promising" if signals else "No signal"\n'
    '    summary = "; ".join(signals) if signals else "neither gamma significant, no AIC gain"\n'
    '    print(f"  {metal} [{verdict}]: {summary}")\n'
    '\n'
    'print("\\n" + "=" * 70)\n'
    'print("Section 13 complete. Ready for GJR-GARCH-X (next prompt).")\n'
    'print("=" * 70)'
))

# ── APPEND TO NOTEBOOK ────────────────────────────────────────────────────────
nb['cells'].extend(new_cells)

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Appended {len(new_cells)} cells (Sections 10-13) to Methodology.ipynb')
print(f'Total cells now: {len(nb["cells"])}')
