"""Append Sections 14-17 (GJR-GARCH-X) to Methodology.ipynb."""
import json, os

REPO = r'c:\Users\PCUser\Documents\GitHub\master_thesis_repo'
NB   = os.path.join(REPO, 'Methodology.ipynb')

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def md(src):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': src}

def code(src):
    return {'cell_type': 'code', 'execution_count': None,
            'metadata': {}, 'outputs': [], 'source': src}

new_cells = []

# ── SECTION 14 — GJR-GARCH-X spec overview (markdown only) ──────────────────
new_cells.append(md(
    '## Section 14 — GJR-GARCH(1,1)-X Specification Overview\n\n'
    '### Variance equation\n\n'
    '$$\n'
    r'\sigma^2_t = \omega + \alpha\,\varepsilon^2_{t-1}'
    r' + \xi\,\varepsilon^2_{t-1}\,I_{t-1}'
    r' + \beta\,\sigma^2_{t-1}'
    r' + \delta_1\,\text{Regressor}_{1,m,t-1}'
    r' + \delta_2\,\text{Regressor}_{2,m,t-1}'
    '\n$$\n\n'
    r'where $I_{t-1} = \mathbf{1}[\varepsilon_{t-1} < 0]$ and $\xi > 0$ captures the '
    r'**return-sign leverage effect** (negative return shocks raise variance above positive shocks '
    r'of equal magnitude). Both `polarity_mean` and `neg_tone_mean` are non-negative by GDELT '
    r'construction, so positivity of $\sigma^2_t$ is preserved without transformation (methodology §3.4.4).'
    '\n\n'
    '### Two specifications\n\n'
    '| Spec | $\\delta_1$ regressor | $\\delta_2$ regressor | EDA VIF | Interpretation |\n'
    '|------|----------------------|----------------------|---------|----------------|\n'
    '| **Main** | `polarity_mean` (total intensity) | `neg_tone_mean` (bad-news) | 2.53 | §3.4.4 primary |\n'
    '| **Auxiliary** | `pos_tone_mean` (good-news) | `neg_tone_mean` (bad-news) | 1.00 | orthogonal decomposition |\n\n'
    'EDA §8b found VIF = 2.53 for (polarity, neg_tone) — below the 5-threshold, so the main spec '
    'is estimable. The auxiliary decomposes polarity into `pos_tone = polarity − neg_tone`, '
    'which by construction is orthogonal to neg_tone (VIF ≈ 1.00), giving a clean '
    '**good-news vs bad-news** test for $\\delta_1$ vs $\\delta_2$.\n\n'
    '### Primary question: sentiment-asymmetry test\n\n'
    'The central hypothesis is $\\delta_2 > \\delta_1$: '
    'bad news amplifies volatility above and beyond what good news predicts. '
    'Formally tested via Wald test $H_0: \\delta_1 = \\delta_2$ (methodology §3.4.4). '
    'This test is **logically separate** from the return-sign asymmetry captured by $\\xi$ — '
    'the question is not whether negative *returns* drive volatility asymmetrically (EDA §5b found '
    'they do not, joint sign-bias $p > 0.47$), but whether negative *news content* does.\n\n'
    '### Implementation path\n\n'
    'GJR-GARCH models **variance** directly (not log-variance), so the two-step auxiliary '
    'regression follows the same structure as Section 11/12 but targets $\\hat{\\sigma}^2_t$ '
    'rather than $\\ln(\\hat{\\sigma}^2_t)$:\n\n'
    '1. Fit GJR-GARCH(1,1,1) without sentiment on the training sample — '
    'recovers $\\omega, \\alpha, \\xi, \\beta$.\n'
    '2. Regress $\\hat{\\sigma}^2_t$ on lagged sentiment regressors via OLS with '
    'Newey-West (HAC) standard errors — recovers $\\delta_1, \\delta_2$.\n\n'
    'In `arch`: `arch_model(y, vol=\'GARCH\', p=1, o=1, q=1, dist=dist)` produces GJR-GARCH '
    'when `o=1`. Parameters named `alpha[1]` (ARCH), `gamma[1]` ($\\xi$, leverage), `beta[1]`.'
))

# ── SECTION 15 — GJR-X main spec (Polarity + NegTone), BIC lag ──────────────
new_cells.append(md(
    '## Section 15 — GJR-GARCH(1,1)-X: Main Spec (Polarity + NegTone), BIC Lag\n\n'
    'EDA §8c BIC-optimal lags: Nd=8, Pr=6, Dy=9, Tb=4. '
    'Both polarity_mean and neg_tone_mean are non-negative, preserving GJR positivity '
    '(methodology §3.4.4). VIF on these regressors should reproduce EDA §8b value of ~2.53.\n\n'
    'Two-step approach: base GJR-GARCH fit on training sample, then HAC-robust OLS of '
    '$\\hat{\\sigma}^2_t$ on lagged sentiment.'
))

new_cells.append(code(
    'import pickle\n'
    'import statsmodels.api as sm\n'
    'import numpy as np\n'
    'from arch import arch_model\n'
    'from statsmodels.stats.outliers_influence import variance_inflation_factor\n'
    '\n'
    'def sig_stars(p):\n'
    '    if p < 0.01:  return \'***\'\n'
    '    if p < 0.05:  return \'**\'\n'
    '    if p < 0.10:  return \'*\'\n'
    '    return \'\'\n'
    '\n'
    'gjrx_main_bic = {}   # {metal: result_dict}\n'
    'gjr_base_bic  = {}   # {metal: ARCHModelResult}  base GJR fits (reused across specs)\n'
    'conv_log_gjr  = []\n'
    '\n'
    'train_mask = df_sent.index < SPLIT_DATE\n'
    '\n'
    'for metal in METALS:\n'
    '    lag_bic = SENT_LAG_BIC[metal]\n'
    '    dist    = ERR_DIST[metal]\n'
    '    ret_train_100 = df_sent.loc[train_mask, f\'{metal}_logret\'].dropna() * 100\n'
    '\n'
    '    # ── Step 1: Fit base GJR-GARCH(1,1,1) ────────────────────────────\n'
    '    am = arch_model(ret_train_100, mean=\'Constant\', vol=\'GARCH\',\n'
    '                    p=1, o=1, q=1, dist=dist)\n'
    '    conv_attempts = []\n'
    '    res = None\n'
    '\n'
    '    for attempt, opts in enumerate([\n'
    '        {},\n'
    '        {\'maxiter\': 2000, \'ftol\': 1e-9},\n'
    '        {\'method\': \'Nelder-Mead\', \'maxiter\': 5000}\n'
    '    ]):\n'
    '        try:\n'
    '            kw = dict(disp=\'off\', show_warning=False, update_freq=0)\n'
    '            if opts:\n'
    '                kw[\'options\'] = opts\n'
    '            r = am.fit(**kw)\n'
    '            if r.convergence_flag == 0:\n'
    '                res = r\n'
    '                break\n'
    '            conv_attempts.append(f\'attempt {attempt+1} flag={r.convergence_flag}\')\n'
    '        except Exception as e:\n'
    '            conv_attempts.append(f\'attempt {attempt+1} err={str(e)[:40]}\')\n'
    '\n'
    '    if res is None:\n'
    '        print(f\'[{metal}] GJR convergence failed: {conv_attempts}\')\n'
    '        gjrx_main_bic[metal] = None\n'
    '        continue\n'
    '\n'
    '    if conv_attempts:\n'
    '        conv_log_gjr.append(f\'{metal} (main-BIC): {conv_attempts}\')\n'
    '        print(f\'[{metal}] Convergence intervention: {conv_attempts}\')\n'
    '\n'
    '    gjr_base_bic[metal] = res\n'
    '\n'
    '    # Extract GJR parameters\n'
    '    params = res.params\n'
    '    omega_g = params.get(\'omega\',    np.nan)\n'
    '    alpha_g = params.get(\'alpha[1]\', np.nan)\n'
    '    xi_g    = params.get(\'gamma[1]\', np.nan)   # GJR asymmetry\n'
    '    beta_g  = params.get(\'beta[1]\',  np.nan)\n'
    '    shape_g = np.nan\n'
    '    for pname in [\'nu\', \'eta\', \'lambda\']:\n'
    '        if pname in params.index:\n'
    '            shape_g = params[pname]; break\n'
    '\n'
    '    # Positivity & stationarity\n'
    '    ab = alpha_g + 0.5 * xi_g + beta_g   # GJR stationarity: alpha + xi/2 + beta < 1\n'
    '    if ab > 0.99:\n'
    '        print(f\'WARNING [{metal}]: GJR persistence alpha+xi/2+beta = {ab:.4f} (near-IGARCH)\')\n'
    '\n'
    '    cond_var = res.conditional_volatility ** 2   # sigma^2_t in (pct_return)^2\n'
    '\n'
    '    # ── Step 2: HAC auxiliary regression on sigma^2 ───────────────────\n'
    '    sent1_col = f\'polarity_mean_std_lag{lag_bic}_{metal}\'\n'
    '    sent2_col = f\'neg_tone_mean_std_lag{lag_bic}_{metal}\'\n'
    '    s1_tr = df_sent.loc[train_mask, sent1_col]\n'
    '    s2_tr = df_sent.loc[train_mask, sent2_col]\n'
    '\n'
    '    aux = pd.DataFrame({\n'
    '        \'var\':   cond_var,\n'
    '        \'sent1\': s1_tr,\n'
    '        \'sent2\': s2_tr\n'
    '    }).dropna()\n'
    '\n'
    '    X_aux = sm.add_constant(aux[[\'sent1\', \'sent2\']])\n'
    '    ols   = sm.OLS(aux[\'var\'], X_aux).fit(\n'
    '                cov_type=\'HAC\', cov_kwds={\'maxlags\': 5, \'use_correction\': True})\n'
    '\n'
    '    delta1   = ols.params[\'sent1\']\n'
    '    delta2   = ols.params[\'sent2\']\n'
    '    d1_t     = ols.tvalues[\'sent1\']\n'
    '    d1_p     = ols.pvalues[\'sent1\']\n'
    '    d2_t     = ols.tvalues[\'sent2\']\n'
    '    d2_p     = ols.pvalues[\'sent2\']\n'
    '\n'
    '    # Joint Wald: H0: delta1 = delta2 = 0\n'
    '    r_joint = np.array([[0, 1, 0], [0, 0, 1]])\n'
    '    wald_joint = ols.wald_test(r_joint, use_f=False, scalar=True)\n'
    '    wj_stat  = float(wald_joint.statistic)\n'
    '    wj_p     = float(wald_joint.pvalue)\n'
    '\n'
    '    # Asymmetry Wald: H0: delta1 = delta2\n'
    '    r_asym = np.array([[0, 1, -1]])\n'
    '    wald_asym = ols.wald_test(r_asym, use_f=False, scalar=True)\n'
    '    wa_stat  = float(wald_asym.statistic)\n'
    '    wa_p     = float(wald_asym.pvalue)\n'
    '\n'
    '    # VIF on the two regressors (should reproduce EDA §8b ~2.53)\n'
    '    vif_data = aux[[\'sent1\', \'sent2\']].copy()\n'
    '    vif_data_c = sm.add_constant(vif_data)\n'
    '    vif1 = variance_inflation_factor(vif_data_c.values, 1)\n'
    '    vif2 = variance_inflation_factor(vif_data_c.values, 2)\n'
    '\n'
    '    # Flag implausibly large coefficients\n'
    '    if abs(delta1) > 5 or abs(delta2) > 5:\n'
    '        print(f\'WARNING [{metal}] main-BIC: large delta (d1={delta1:.3f}, d2={delta2:.3f})\')\n'
    '        print(f\'  sent1 stats: mean={s1_tr.mean():.3f}, std={s1_tr.std():.3f}, max={s1_tr.max():.3f}\')\n'
    '        print(f\'  sent2 stats: mean={s2_tr.mean():.3f}, std={s2_tr.std():.3f}, max={s2_tr.max():.3f}\')\n'
    '\n'
    '    # Check positivity of sentiment-adjusted fitted variance\n'
    '    var_adj_check = cond_var + delta1 * s1_tr + delta2 * s2_tr\n'
    '    n_neg = (var_adj_check.dropna() <= 0).sum()\n'
    '    if n_neg > 0:\n'
    '        print(f\'WARNING [{metal}] main-BIC: {n_neg} in-sample obs with adjusted sigma^2 <= 0\')\n'
    '\n'
    '    rdict = {\n'
    '        \'metal\': metal, \'spec\': \'main\', \'lag\': lag_bic,\n'
    '        \'arch_res\': res, \'ols_aux\': ols,\n'
    '        \'omega\': omega_g, \'alpha\': alpha_g, \'xi\': xi_g,\n'
    '        \'beta\': beta_g, \'shape\': shape_g,\n'
    '        \'persistence\': ab,\n'
    '        \'loglik\': res.loglikelihood, \'aic\': res.aic, \'bic\': res.bic,\n'
    '        \'delta1\': delta1, \'delta2\': delta2,\n'
    '        \'d1_t\': d1_t, \'d1_p\': d1_p, \'d2_t\': d2_t, \'d2_p\': d2_p,\n'
    '        \'wald_joint_stat\': wj_stat, \'wald_joint_p\': wj_p,\n'
    '        \'wald_asym_stat\': wa_stat, \'wald_asym_p\': wa_p,\n'
    '        \'vif1\': vif1, \'vif2\': vif2,\n'
    '    }\n'
    '    gjrx_main_bic[metal] = rdict\n'
    '\n'
    '    with open(f\'outputs/gjrx_main_bic_{metal}.pkl\', \'wb\') as fh:\n'
    '        pickle.dump(rdict, fh)\n'
    '\n'
    '    print(f\'[{metal}] main BIC lag={lag_bic}: \'\n'
    '          f\'d1(pol)={delta1:.4f}(t={d1_t:.2f},p={d1_p:.3f}) \'\n'
    '          f\'d2(neg)={delta2:.4f}(t={d2_t:.2f},p={d2_p:.3f}) \'\n'
    '          f\'Wjoint-p={wj_p:.4f} Wasym-p={wa_p:.4f} \'\n'
    '          f\'VIF={vif1:.2f}/{vif2:.2f}\')\n'
    '\n'
    'print(\'\\nSection 15 complete.\')'
))

new_cells.append(code(
    '# ── Full parameter table for GJR-X main BIC fits ──────────────────────\n'
    'print("GJR-GARCH(1,1)-X Parameter Table — Main Spec (Polarity + NegTone), BIC lag")\n'
    'print("=" * 108)\n'
    'hdr = (f"  {\'Metal\':<6} {\'Lag\':>4} {\'omega\':>10} {\'alpha\':>8} {\'xi\':>8} "\n'
    '       f"{\'beta\':>8} {\'shape\':>7} {\'delta1\':>8} {\'d1_p\':>7} "\n'
    '       f"{\'delta2\':>8} {\'d2_p\':>7} {\'Wjt-p\':>7} {\'Wasm-p\':>7} "\n'
    '       f"{\'VIF1\':>6} {\'VIF2\':>6} {\'LogLik\':>9}")\n'
    'print(hdr)\n'
    'print("  " + "-" * (len(hdr)-2))\n'
    'for metal in METALS:\n'
    '    r = gjrx_main_bic.get(metal)\n'
    '    if r is None:\n'
    '        print(f"  {metal:<6} CONVERGENCE FAILED")\n'
    '        continue\n'
    '    print(\n'
    '        f"  {metal:<6} {r[\'lag\']:>4} {r[\'omega\']:>10.5f} {r[\'alpha\']:>8.5f} "\n'
    '        f"{r[\'xi\']:>8.5f} {r[\'beta\']:>8.5f} {r[\'shape\']:>7.3f} "\n'
    '        f"{r[\'delta1\']:>8.4f}{sig_stars(r[\'d1_p\']):3s} {r[\'d1_p\']:>7.4f} "\n'
    '        f"{r[\'delta2\']:>8.4f}{sig_stars(r[\'d2_p\']):3s} {r[\'d2_p\']:>7.4f} "\n'
    '        f"{r[\'wald_joint_p\']:>7.4f} {r[\'wald_asym_p\']:>7.4f} "\n'
    '        f"{r[\'vif1\']:>6.2f} {r[\'vif2\']:>6.2f} {r[\'loglik\']:>9.2f}"\n'
    '    )\n'
    'print("\\nNote: VIF1/VIF2 are for polarity and neg_tone — EDA §8b target: ~2.53")\n'
    'print("Wasym-p = Wald test delta1=delta2 (sentiment asymmetry); Wjt-p = delta1=delta2=0")'
))

# ── SECTION 16 — GJR-X auxiliary spec (PosTone + NegTone), BIC lag ──────────
new_cells.append(md(
    '## Section 16 — GJR-GARCH(1,1)-X: Auxiliary Spec (PosTone + NegTone), BIC Lag\n\n'
    'EDA §8b: VIF(pos_tone, neg_tone) = 1.00 — by construction orthogonal since '
    '`pos_tone = polarity − neg_tone` partitions polarity into two non-overlapping components. '
    'The $\\delta_1$ vs $\\delta_2$ comparison here maps directly to good-news vs bad-news, '
    'without the multicollinearity that complicates interpretation in the main spec.\n\n'
    'The base GJR-GARCH fit is **identical** to Section 15 (same model, same training data) — '
    'only the auxiliary regression changes. `gjr_base_bic` is reused.'
))

new_cells.append(code(
    '# GJR-X auxiliary spec (PosTone + NegTone), BIC lag\n'
    '# Base GJR fit reused from Section 15; only auxiliary OLS changes\n'
    '# VIF(pos_tone, neg_tone) = 1.00 — EDA §8b, near-orthogonal decomposition\n'
    '\n'
    'gjrx_aux_bic = {}   # {metal: result_dict}\n'
    '\n'
    'for metal in METALS:\n'
    '    lag_bic = SENT_LAG_BIC[metal]\n'
    '\n'
    '    if metal not in gjr_base_bic:\n'
    '        print(f\'[{metal}] No base GJR fit from Section 15 — skipping aux BIC\')\n'
    '        gjrx_aux_bic[metal] = None\n'
    '        continue\n'
    '\n'
    '    res = gjr_base_bic[metal]   # reuse base GJR from Section 15\n'
    '    params = res.params\n'
    '    omega_g = params.get(\'omega\',    np.nan)\n'
    '    alpha_g = params.get(\'alpha[1]\', np.nan)\n'
    '    xi_g    = params.get(\'gamma[1]\', np.nan)\n'
    '    beta_g  = params.get(\'beta[1]\',  np.nan)\n'
    '    shape_g = np.nan\n'
    '    for pname in [\'nu\', \'eta\', \'lambda\']:\n'
    '        if pname in params.index:\n'
    '            shape_g = params[pname]; break\n'
    '    ab = alpha_g + 0.5 * xi_g + beta_g\n'
    '\n'
    '    cond_var = res.conditional_volatility ** 2\n'
    '\n'
    '    # Auxiliary spec: pos_tone + neg_tone\n'
    '    sent1_col = f\'pos_tone_mean_std_lag{lag_bic}_{metal}\'\n'
    '    sent2_col = f\'neg_tone_mean_std_lag{lag_bic}_{metal}\'\n'
    '    s1_tr = df_sent.loc[train_mask, sent1_col]\n'
    '    s2_tr = df_sent.loc[train_mask, sent2_col]\n'
    '\n'
    '    aux = pd.DataFrame({\n'
    '        \'var\':   cond_var,\n'
    '        \'sent1\': s1_tr,\n'
    '        \'sent2\': s2_tr\n'
    '    }).dropna()\n'
    '\n'
    '    X_aux = sm.add_constant(aux[[\'sent1\', \'sent2\']])\n'
    '    ols   = sm.OLS(aux[\'var\'], X_aux).fit(\n'
    '                cov_type=\'HAC\', cov_kwds={\'maxlags\': 5, \'use_correction\': True})\n'
    '\n'
    '    delta1 = ols.params[\'sent1\']\n'
    '    delta2 = ols.params[\'sent2\']\n'
    '    d1_t   = ols.tvalues[\'sent1\']\n'
    '    d1_p   = ols.pvalues[\'sent1\']\n'
    '    d2_t   = ols.tvalues[\'sent2\']\n'
    '    d2_p   = ols.pvalues[\'sent2\']\n'
    '\n'
    '    r_joint = np.array([[0, 1, 0], [0, 0, 1]])\n'
    '    wald_joint = ols.wald_test(r_joint, use_f=False, scalar=True)\n'
    '    wj_p = float(wald_joint.pvalue)\n'
    '    wj_stat = float(wald_joint.statistic)\n'
    '\n'
    '    r_asym = np.array([[0, 1, -1]])\n'
    '    wald_asym = ols.wald_test(r_asym, use_f=False, scalar=True)\n'
    '    wa_p = float(wald_asym.pvalue)\n'
    '    wa_stat = float(wald_asym.statistic)\n'
    '\n'
    '    # VIF (should be ~1.00 for aux spec)\n'
    '    vif_data_c = sm.add_constant(aux[[\'sent1\', \'sent2\']])\n'
    '    vif1 = variance_inflation_factor(vif_data_c.values, 1)\n'
    '    vif2 = variance_inflation_factor(vif_data_c.values, 2)\n'
    '\n'
    '    if abs(delta1) > 5 or abs(delta2) > 5:\n'
    '        print(f\'WARNING [{metal}] aux-BIC: large delta (d1={delta1:.3f}, d2={delta2:.3f})\')\n'
    '\n'
    '    var_adj_check = cond_var + delta1 * s1_tr + delta2 * s2_tr\n'
    '    n_neg = (var_adj_check.dropna() <= 0).sum()\n'
    '    if n_neg > 0:\n'
    '        print(f\'WARNING [{metal}] aux-BIC: {n_neg} obs with adjusted sigma^2 <= 0\')\n'
    '\n'
    '    rdict = {\n'
    '        \'metal\': metal, \'spec\': \'aux\', \'lag\': lag_bic,\n'
    '        \'arch_res\': res, \'ols_aux\': ols,\n'
    '        \'omega\': omega_g, \'alpha\': alpha_g, \'xi\': xi_g,\n'
    '        \'beta\': beta_g, \'shape\': shape_g,\n'
    '        \'persistence\': ab,\n'
    '        \'loglik\': res.loglikelihood, \'aic\': res.aic, \'bic\': res.bic,\n'
    '        \'delta1\': delta1, \'delta2\': delta2,\n'
    '        \'d1_t\': d1_t, \'d1_p\': d1_p, \'d2_t\': d2_t, \'d2_p\': d2_p,\n'
    '        \'wald_joint_stat\': wj_stat, \'wald_joint_p\': wj_p,\n'
    '        \'wald_asym_stat\': wa_stat, \'wald_asym_p\': wa_p,\n'
    '        \'vif1\': vif1, \'vif2\': vif2,\n'
    '    }\n'
    '    gjrx_aux_bic[metal] = rdict\n'
    '\n'
    '    with open(f\'outputs/gjrx_aux_bic_{metal}.pkl\', \'wb\') as fh:\n'
    '        pickle.dump(rdict, fh)\n'
    '\n'
    '    print(f\'[{metal}] aux BIC lag={lag_bic}: \'\n'
    '          f\'d1(pos)={delta1:.4f}(t={d1_t:.2f},p={d1_p:.3f}) \'\n'
    '          f\'d2(neg)={delta2:.4f}(t={d2_t:.2f},p={d2_p:.3f}) \'\n'
    '          f\'Wjoint-p={wj_p:.4f} Wasym-p={wa_p:.4f} \'\n'
    '          f\'VIF={vif1:.2f}/{vif2:.2f}\')\n'
    '\n'
    'print(\'\\nSection 16 complete.\')'
))

new_cells.append(code(
    '# ── Side-by-side: main spec vs auxiliary spec, BIC lag ─────────────────\n'
    '# Key: if both specs show delta2 > delta1, asymmetry is robust to VIF\n'
    '\n'
    'print("GJR-X Side-by-Side: Main (Polarity+NegTone) vs Auxiliary (PosTone+NegTone) — BIC lag")\n'
    'print("=" * 100)\n'
    'print(f"  {\'Metal\':<6} {\'Lag\':>4}  "\n'
    '      f"{\'d1_main(pol)\':>13} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'d2_main(neg)\':>13} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'d1_aux(pos)\':>13} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'d2_aux(neg)\':>13} {\'t\':>6} {\'p\':>6}")\n'
    'print("  " + "-" * 98)\n'
    'for metal in METALS:\n'
    '    rm = gjrx_main_bic.get(metal)\n'
    '    ra = gjrx_aux_bic.get(metal)\n'
    '    lag = SENT_LAG_BIC[metal]\n'
    '    d1m = rm[\'delta1\'] if rm else np.nan; d1m_t = rm[\'d1_t\'] if rm else np.nan\n'
    '    d1m_p = rm[\'d1_p\'] if rm else np.nan\n'
    '    d2m = rm[\'delta2\'] if rm else np.nan; d2m_t = rm[\'d2_t\'] if rm else np.nan\n'
    '    d2m_p = rm[\'d2_p\'] if rm else np.nan\n'
    '    d1a = ra[\'delta1\'] if ra else np.nan; d1a_t = ra[\'d1_t\'] if ra else np.nan\n'
    '    d1a_p = ra[\'d1_p\'] if ra else np.nan\n'
    '    d2a = ra[\'delta2\'] if ra else np.nan; d2a_t = ra[\'d2_t\'] if ra else np.nan\n'
    '    d2a_p = ra[\'d2_p\'] if ra else np.nan\n'
    '    print(f"  {metal:<6} {lag:>4}  "\n'
    '          f"{d1m:>13.4f}{sig_stars(d1m_p):3s} {d1m_t:>6.2f} {d1m_p:>6.3f}  "\n'
    '          f"{d2m:>13.4f}{sig_stars(d2m_p):3s} {d2m_t:>6.2f} {d2m_p:>6.3f}  "\n'
    '          f"{d1a:>13.4f}{sig_stars(d1a_p):3s} {d1a_t:>6.2f} {d1a_p:>6.3f}  "\n'
    '          f"{d2a:>13.4f}{sig_stars(d2a_p):3s} {d2a_t:>6.2f} {d2a_p:>6.3f}")\n'
    '\n'
    'print("\\nAsymmetry Wald test (H0: delta1=delta2):")\n'
    'print(f"  {\'Metal\':<6} {\'Main Wasym-p\':>14} {\'Aux Wasym-p\':>14}")\n'
    'for metal in METALS:\n'
    '    rm = gjrx_main_bic.get(metal)\n'
    '    ra = gjrx_aux_bic.get(metal)\n'
    '    wm = rm[\'wald_asym_p\'] if rm else np.nan\n'
    '    wa = ra[\'wald_asym_p\'] if ra else np.nan\n'
    '    print(f"  {metal:<6} {wm:>14.4f} {wa:>14.4f}")'
))

new_cells.append(md(
    '### Section 16 — Main vs Auxiliary commentary\n\n'
    'The auxiliary specification (PosTone + NegTone) has near-zero collinearity (VIF ≈ 1.00), '
    'making it the **more trustworthy reading for asymmetry**: any difference in $\\delta_1$ vs '
    '$\\delta_2$ significance is not an artifact of multicollinearity.\n\n'
    'Interpretation:\n'
    '- If auxiliary shows $\\delta_2 > \\delta_1$ with Wald $p < 0.10$: bad news drives volatility '
    'more than good news — the negativity-bias hypothesis is supported.\n'
    '- If main and auxiliary diverge in sign or significance: the main spec\'s $\\delta_1$ conflates '
    'positive and negative intensity; the auxiliary gives the cleaner estimate.\n'
    '- If neither $\\delta$ is significant in either spec: no sentiment channel in the variance equation, '
    'consistent with Tb\'s EDA §8 Granger null and possibly Nd.'
))

# ── SECTION 17 — L=1 refits, forecasts, diagnostics ─────────────────────────
new_cells.append(md(
    '## Section 17 — GJR-X Robustness (L=1), Forecasts, and Diagnostics\n\n'
    'Sub-sections:\n'
    '- **17a**: Both main and auxiliary specs re-fitted at L=1 (Granger-motivated)\n'
    '- **17b**: Expanding-window one-step-ahead forecasts for all four GJR-X variants\n'
    '- **17c**: In-sample Ljung-Box and Engle-Ng diagnostics for the main BIC spec\n'
    '- **17d**: Full readiness summary'
))

# 17a — L=1 refits
new_cells.append(md(
    '### Section 17a — GJR-X at L=1: Main and Auxiliary Specifications\n\n'
    'Granger lag-1 evidence (EDA §8): Nd→log_volume p=0.008, Pr→tone p=0.039, '
    'Dy→log_volume p=0.002. These are for *tone* and *volume* rather than *polarity* and '
    '*neg_tone*, but the lag-1 structure motivates checking all sentiment channels at L=1. '
    'The same base GJR-GARCH fit is reused (only the auxiliary regression changes).'
))

new_cells.append(code(
    '# GJR-X L=1 refits — main (polarity + neg_tone) and auxiliary (pos_tone + neg_tone)\n'
    '# Granger evidence at lag 1 motivates this robustness check — EDA §8\n'
    '# Base GJR reused from Section 15; only auxiliary OLS changes\n'
    '\n'
    'gjrx_main_l1 = {}\n'
    'gjrx_aux_l1  = {}\n'
    '\n'
    'for metal in METALS:\n'
    '    if metal not in gjr_base_bic:\n'
    '        print(f\'[{metal}] No base GJR fit — skipping L=1\')\n'
    '        gjrx_main_l1[metal] = None\n'
    '        gjrx_aux_l1[metal]  = None\n'
    '        continue\n'
    '\n'
    '    res = gjr_base_bic[metal]\n'
    '    params = res.params\n'
    '    omega_g = params.get(\'omega\',    np.nan)\n'
    '    alpha_g = params.get(\'alpha[1]\', np.nan)\n'
    '    xi_g    = params.get(\'gamma[1]\', np.nan)\n'
    '    beta_g  = params.get(\'beta[1]\',  np.nan)\n'
    '    shape_g = np.nan\n'
    '    for pname in [\'nu\', \'eta\', \'lambda\']:\n'
    '        if pname in params.index:\n'
    '            shape_g = params[pname]; break\n'
    '    ab = alpha_g + 0.5 * xi_g + beta_g\n'
    '    cond_var = res.conditional_volatility ** 2\n'
    '\n'
    '    for spec_name, s1_col, s2_col, out_dict, out_key in [\n'
    '        (\'main\',\n'
    '         f\'polarity_mean_std_lag1_{metal}\',\n'
    '         f\'neg_tone_mean_std_lag1_{metal}\',\n'
    '         gjrx_main_l1, metal),\n'
    '        (\'aux\',\n'
    '         f\'pos_tone_mean_std_lag1_{metal}\',\n'
    '         f\'neg_tone_mean_std_lag1_{metal}\',\n'
    '         gjrx_aux_l1, metal),\n'
    '    ]:\n'
    '        s1_tr = df_sent.loc[train_mask, s1_col]\n'
    '        s2_tr = df_sent.loc[train_mask, s2_col]\n'
    '\n'
    '        aux_df = pd.DataFrame({\n'
    '            \'var\':   cond_var,\n'
    '            \'sent1\': s1_tr,\n'
    '            \'sent2\': s2_tr\n'
    '        }).dropna()\n'
    '\n'
    '        X_aux = sm.add_constant(aux_df[[\'sent1\', \'sent2\']])\n'
    '        ols   = sm.OLS(aux_df[\'var\'], X_aux).fit(\n'
    '                    cov_type=\'HAC\', cov_kwds={\'maxlags\': 5, \'use_correction\': True})\n'
    '\n'
    '        delta1 = ols.params[\'sent1\']; d1_t = ols.tvalues[\'sent1\']; d1_p = ols.pvalues[\'sent1\']\n'
    '        delta2 = ols.params[\'sent2\']; d2_t = ols.tvalues[\'sent2\']; d2_p = ols.pvalues[\'sent2\']\n'
    '\n'
    '        r_joint = np.array([[0, 1, 0], [0, 0, 1]])\n'
    '        wj = ols.wald_test(r_joint, use_f=False, scalar=True)\n'
    '        r_asym = np.array([[0, 1, -1]])\n'
    '        wa = ols.wald_test(r_asym,  use_f=False, scalar=True)\n'
    '\n'
    '        vif_dc = sm.add_constant(aux_df[[\'sent1\', \'sent2\']])\n'
    '        vif1 = variance_inflation_factor(vif_dc.values, 1)\n'
    '        vif2 = variance_inflation_factor(vif_dc.values, 2)\n'
    '\n'
    '        var_adj = cond_var + delta1 * s1_tr + delta2 * s2_tr\n'
    '        n_neg   = (var_adj.dropna() <= 0).sum()\n'
    '        if n_neg > 0:\n'
    '            print(f\'WARNING [{metal}] {spec_name}-L1: {n_neg} obs adjusted sigma^2 <= 0\')\n'
    '\n'
    '        rdict = {\n'
    '            \'metal\': metal, \'spec\': spec_name, \'lag\': 1,\n'
    '            \'arch_res\': res, \'ols_aux\': ols,\n'
    '            \'omega\': omega_g, \'alpha\': alpha_g, \'xi\': xi_g,\n'
    '            \'beta\': beta_g, \'shape\': shape_g, \'persistence\': ab,\n'
    '            \'loglik\': res.loglikelihood, \'aic\': res.aic, \'bic\': res.bic,\n'
    '            \'delta1\': delta1, \'delta2\': delta2,\n'
    '            \'d1_t\': d1_t, \'d1_p\': d1_p, \'d2_t\': d2_t, \'d2_p\': d2_p,\n'
    '            \'wald_joint_stat\': float(wj.statistic), \'wald_joint_p\': float(wj.pvalue),\n'
    '            \'wald_asym_stat\': float(wa.statistic), \'wald_asym_p\': float(wa.pvalue),\n'
    '            \'vif1\': vif1, \'vif2\': vif2,\n'
    '        }\n'
    '        out_dict[out_key] = rdict\n'
    '\n'
    '        pkl_path = f\'outputs/gjrx_{spec_name}_l1_{metal}.pkl\'\n'
    '        with open(pkl_path, \'wb\') as fh:\n'
    '            pickle.dump(rdict, fh)\n'
    '\n'
    '        print(f\'[{metal}] {spec_name} L1: \'\n'
    '              f\'d1={delta1:.4f}(t={d1_t:.2f},p={d1_p:.3f}) \'\n'
    '              f\'d2={delta2:.4f}(t={d2_t:.2f},p={d2_p:.3f}) \'\n'
    '              f\'Wjoint-p={float(wj.pvalue):.4f} Wasym-p={float(wa.pvalue):.4f}\')\n'
    '\n'
    'print(\'\\nSection 17a complete.\')\n'
    '\n'
    '# ── Comparison table: BIC vs L=1 for both specs ─────────────────────\n'
    'print("\\nGJR-X: BIC lag vs L=1 — delta1 and delta2 comparison")\n'
    'print("=" * 106)\n'
    'print(f"  {\'Metal\':<6}  "\n'
    '      f"{\'d1_main_BIC\':>12} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'d1_main_L1\':>12} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'d2_main_BIC\':>12} {\'t\':>6} {\'p\':>6}  "\n'
    '      f"{\'d2_main_L1\':>12} {\'t\':>6} {\'p\':>6}")\n'
    'print("  " + "-" * 104)\n'
    'for metal in METALS:\n'
    '    rb = gjrx_main_bic.get(metal)\n'
    '    rl = gjrx_main_l1.get(metal)\n'
    '    d1b = rb[\'delta1\'] if rb else np.nan; d1bt = rb[\'d1_t\'] if rb else np.nan; d1bp = rb[\'d1_p\'] if rb else np.nan\n'
    '    d1l = rl[\'delta1\'] if rl else np.nan; d1lt = rl[\'d1_t\'] if rl else np.nan; d1lp = rl[\'d1_p\'] if rl else np.nan\n'
    '    d2b = rb[\'delta2\'] if rb else np.nan; d2bt = rb[\'d2_t\'] if rb else np.nan; d2bp = rb[\'d2_p\'] if rb else np.nan\n'
    '    d2l = rl[\'delta2\'] if rl else np.nan; d2lt = rl[\'d2_t\'] if rl else np.nan; d2lp = rl[\'d2_p\'] if rl else np.nan\n'
    '    print(f"  {metal:<6}  "\n'
    '          f"{d1b:>12.4f}{sig_stars(d1bp):3s} {d1bt:>6.2f} {d1bp:>6.3f}  "\n'
    '          f"{d1l:>12.4f}{sig_stars(d1lp):3s} {d1lt:>6.2f} {d1lp:>6.3f}  "\n'
    '          f"{d2b:>12.4f}{sig_stars(d2bp):3s} {d2bt:>6.2f} {d2bp:>6.3f}  "\n'
    '          f"{d2l:>12.4f}{sig_stars(d2lp):3s} {d2lt:>6.2f} {d2lp:>6.3f}")'
))

# 17b — Forecasts
new_cells.append(md(
    '### Section 17b — GJR-X Expanding-Window Forecasts\n\n'
    'Four variants: main BIC, main L=1, aux BIC, aux L=1. '
    'At each test date, GJR-GARCH is refitted on the expanding window, '
    'one-step-ahead conditional variance obtained, and fixed $\\hat{\\delta}_1, \\hat{\\delta}_2$ '
    'from the training-sample auxiliary regression applied additively:\n\n'
    '$$\\hat{\\sigma}^2_{t+1} = \\hat{\\sigma}^2_{t+1|t,\\text{GJR}} + \\hat{\\delta}_1 \\cdot s_{1,t-L+1} '
    '+ \\hat{\\delta}_2 \\cdot s_{2,t-L+1}$$\n\n'
    'Clipped to $10^{-12}$ before dividing by $10^4$ to ensure positivity.'
))

new_cells.append(code(
    'import time\n'
    '\n'
    '# Expanding-window GJR-X forecasts — all 4 variants\n'
    '# Uses fixed deltas from training-sample auxiliary regression (Sections 15/16/17a)\n'
    '\n'
    'gjrx_forecasts = {}   # keyed by (spec, lag_key, metal)\n'
    '\n'
    'VARIANTS = [\n'
    '    (\'main\', \'bic\', gjrx_main_bic,\n'
    '     lambda m, L: (f\'polarity_mean_std_lag{L}_{m}\', f\'neg_tone_mean_std_lag{L}_{m}\')),\n'
    '    (\'main\', \'l1\',  gjrx_main_l1,\n'
    '     lambda m, L: (f\'polarity_mean_std_lag1_{m}\', f\'neg_tone_mean_std_lag1_{m}\')),\n'
    '    (\'aux\',  \'bic\', gjrx_aux_bic,\n'
    '     lambda m, L: (f\'pos_tone_mean_std_lag{L}_{m}\', f\'neg_tone_mean_std_lag{L}_{m}\')),\n'
    '    (\'aux\',  \'l1\',  gjrx_aux_l1,\n'
    '     lambda m, L: (f\'pos_tone_mean_std_lag1_{m}\', f\'neg_tone_mean_std_lag1_{m}\')),\n'
    ']\n'
    '\n'
    'REFIT_FREQ_GJR = 1\n'
    'test_dates  = df_sent.index[df_sent.index >= SPLIT_DATE]\n'
    'all_dates   = df_sent.index\n'
    '\n'
    'total_start_gjr = time.time()\n'
    '\n'
    'for metal in METALS:\n'
    '    ret_full_100 = df_sent[f\'{metal}_logret\'].dropna() * 100\n'
    '    dist         = ERR_DIST[metal]\n'
    '    lag_bic      = SENT_LAG_BIC[metal]\n'
    '\n'
    '    # Warm-start from the training fit\n'
    '    base_res = gjr_base_bic.get(metal)\n'
    '    if base_res is None:\n'
    '        print(f\'[{metal}] No base GJR fit — skipping all GJR-X forecasts\')\n'
    '        continue\n'
    '\n'
    '    # Pre-extract deltas for all 4 variants\n'
    '    variant_deltas = []\n'
    '    for spec, lag_key, rdict_src, col_fn in VARIANTS:\n'
    '        rd = rdict_src.get(metal)\n'
    '        if rd is None:\n'
    '            variant_deltas.append((spec, lag_key, 0.0, 0.0, \'na\', \'na\'))\n'
    '            continue\n'
    '        L_val = SENT_LAG_BIC[metal] if lag_key == \'bic\' else 1\n'
    '        s1c, s2c = col_fn(metal, L_val)\n'
    '        variant_deltas.append((spec, lag_key, rd[\'delta1\'], rd[\'delta2\'], s1c, s2c))\n'
    '\n'
    '    # Per-variant forecast lists\n'
    '    fc_lists = {(v[0], v[1]): [] for v in variant_deltas}\n'
    '\n'
    '    res_gjr    = base_res\n'
    '    metal_start = time.time()\n'
    '    step_count  = 0\n'
    '\n'
    '    for t_date in test_dates:\n'
    '        t_pos      = all_dates.get_loc(t_date)\n'
    '        ret_window = ret_full_100.iloc[:t_pos]\n'
    '\n'
    '        var_base_pct = np.nan\n'
    '        try:\n'
    '            am_gjr = arch_model(ret_window, mean=\'Constant\', vol=\'GARCH\',\n'
    '                                p=1, o=1, q=1, dist=dist)\n'
    '            if step_count % REFIT_FREQ_GJR == 0:\n'
    '                r_new = am_gjr.fit(disp=\'off\', show_warning=False, update_freq=0,\n'
    '                                   starting_values=res_gjr.params.values)\n'
    '                if r_new.convergence_flag == 0:\n'
    '                    res_gjr = r_new\n'
    '                else:\n'
    '                    r_new2 = am_gjr.fit(disp=\'off\', show_warning=False, update_freq=0)\n'
    '                    if r_new2.convergence_flag == 0:\n'
    '                        res_gjr = r_new2\n'
    '\n'
    '            fcast = res_gjr.forecast(horizon=1, reindex=False)\n'
    '            var_base_pct = fcast.variance.iloc[-1, 0]\n'
    '        except Exception:\n'
    '            pass\n'
    '\n'
    '        for spec, lag_key, d1, d2, s1c, s2c in variant_deltas:\n'
    '            if s1c == \'na\':\n'
    '                fc_lists[(spec, lag_key)].append((t_date, np.nan))\n'
    '                continue\n'
    '            if np.isnan(var_base_pct):\n'
    '                fc_lists[(spec, lag_key)].append((t_date, np.nan))\n'
    '                continue\n'
    '\n'
    '            s1v = df_sent.get(s1c, pd.Series(dtype=float))\n'
    '            s2v = df_sent.get(s2c, pd.Series(dtype=float))\n'
    '            s1_val = 0.0 if t_date not in s1v.index or pd.isna(s1v.loc[t_date]) else float(s1v.loc[t_date])\n'
    '            s2_val = 0.0 if t_date not in s2v.index or pd.isna(s2v.loc[t_date]) else float(s2v.loc[t_date])\n'
    '\n'
    '            var_adj = max(var_base_pct + d1 * s1_val + d2 * s2_val, 1e-12)\n'
    '            fc_lists[(spec, lag_key)].append((t_date, var_adj / 1e4))\n'
    '\n'
    '        step_count += 1\n'
    '        if REFIT_FREQ_GJR == 1 and (time.time() - metal_start) > 900 and step_count < 50:\n'
    '            REFIT_FREQ_GJR = 22\n'
    '            print(f\'[{metal}] GJR slow — switching to 22-step refit\')\n'
    '\n'
    '    for (spec, lag_key), fc_list in fc_lists.items():\n'
    '        fc_s = pd.Series({d: v for d, v in fc_list}, name=\'forecast_var\')\n'
    '        gjrx_forecasts[(spec, lag_key, metal)] = fc_s\n'
    '        fname = f\'outputs/forecasts_gjrx_{spec}_{lag_key}_{metal}.pkl\'\n'
    '        with open(fname, \'wb\') as fh:\n'
    '            pickle.dump(fc_s, fh)\n'
    '\n'
    '    elapsed = time.time() - metal_start\n'
    '    print(f\'[{metal}] GJR-X forecasts done — {len(test_dates)} steps, {elapsed:.1f}s\')\n'
    '\n'
    '    if (time.time() - total_start_gjr) > 1800:\n'
    '        REFIT_FREQ_GJR = 22\n'
    '\n'
    'print(f\'\\nGJR-X forecasts complete. Refit frequency: every {REFIT_FREQ_GJR} step(s).\')'
))

# 17c — Diagnostics
new_cells.append(md(
    '### Section 17c — In-Sample Diagnostics on GJR-GARCH Base (Main BIC)\n\n'
    'Ljung-Box on standardised residuals and squared standardised residuals at lags 5/10/20, '
    'plus Engle-Ng sign bias test. '
    'Sign bias is expected to remain insignificant (EDA §5b). '
    'Compared against GARCH(1,1) (Section 8) and EGARCH-X (Section 13b).'
))

new_cells.append(code(
    '# In-sample diagnostics: GJR base (main BIC fits) vs GARCH(1,1) and EGARCH\n'
    '# ARCH-LM p~0 all metals (EDA §5) — GJR should absorb; sign bias expected null\n'
    'from statsmodels.stats.diagnostic import acorr_ljungbox\n'
    '\n'
    'gjr_diag_rows = []\n'
    'gjr_sb_rows   = []\n'
    '\n'
    'for metal in METALS:\n'
    '    rm = gjrx_main_bic.get(metal)\n'
    '    if rm is None:\n'
    '        print(f\'[{metal}] No GJR fit — skipping diagnostics\')\n'
    '        continue\n'
    '    res  = rm[\'arch_res\']\n'
    '    zhat = res.std_resid.dropna()\n'
    '\n'
    '    for lag in [5, 10, 20]:\n'
    '        lb_z  = acorr_ljungbox(zhat,      lags=[lag], return_df=True)\n'
    '        lb_z2 = acorr_ljungbox(zhat ** 2, lags=[lag], return_df=True)\n'
    '        gjr_diag_rows.append({\'Metal\': metal, \'Test\': \'LB-z\',  \'Lag\': lag,\n'
    '                               \'GJR_Stat\': lb_z[\'lb_stat\'].iloc[0],\n'
    '                               \'GJR_p\':   lb_z[\'lb_pvalue\'].iloc[0]})\n'
    '        gjr_diag_rows.append({\'Metal\': metal, \'Test\': \'LB-z^2\', \'Lag\': lag,\n'
    '                               \'GJR_Stat\': lb_z2[\'lb_stat\'].iloc[0],\n'
    '                               \'GJR_p\':   lb_z2[\'lb_pvalue\'].iloc[0]})\n'
    '\n'
    '    # Engle-Ng sign bias on GJR residuals\n'
    '    z     = zhat; z_lag = z.shift(1); dep = z ** 2\n'
    '    mv = z_lag.notna()\n'
    '    dep_v = dep[mv]; zl_v = z_lag[mv]\n'
    '    S_neg = (zl_v < 0).astype(float)\n'
    '    X_sb = sm.add_constant(pd.DataFrame({\n'
    '        \'S_neg\': S_neg, \'neg_size\': S_neg * zl_v, \'pos_size\': (1-S_neg) * zl_v}))\n'
    '    ols_sb = sm.OLS(dep_v, X_sb).fit()\n'
    '    f_t = ols_sb.f_test([[0,1,0,0],[0,0,1,0],[0,0,0,1]])\n'
    '    gjr_sb_rows.append({\'Metal\': metal,\n'
    '                         \'SignBias_t\': ols_sb.tvalues[\'S_neg\'],\n'
    '                         \'SignBias_p\': ols_sb.pvalues[\'S_neg\'],\n'
    '                         \'NegSize_t\':  ols_sb.tvalues[\'neg_size\'],\n'
    '                         \'NegSize_p\':  ols_sb.pvalues[\'neg_size\'],\n'
    '                         \'JointF\':     float(f_t.fvalue),\n'
    '                         \'JointP\':     float(f_t.pvalue)})\n'
    '\n'
    'gjr_diag_df = pd.DataFrame(gjr_diag_rows)\n'
    'gjr_sb_df   = pd.DataFrame(gjr_sb_rows)\n'
    '\n'
    '# Merge with GARCH11 and EGARCH diagnostics\n'
    'gjr_compare = gjr_diag_df.merge(\n'
    '    diag_df.rename(columns={\'Stat\': \'GARCH11_Stat\', \'p-value\': \'GARCH11_p\'}),\n'
    '    on=[\'Metal\', \'Test\', \'Lag\'], how=\'left\'\n'
    ').merge(\n'
    '    eg_diag_df.rename(columns={\'EGARCH_Stat\': \'EGARCH_Stat\', \'EGARCH_p\': \'EGARCH_p\'}),\n'
    '    on=[\'Metal\', \'Test\', \'Lag\'], how=\'left\'\n'
    ')\n'
    '\n'
    'print("Ljung-Box: GJR vs EGARCH vs GARCH(1,1) — training sample")\n'
    'print("=" * 82)\n'
    'print(gjr_compare.to_string(index=False, float_format=\'{:.4f}\'.format))\n'
    '\n'
    'print("\\nEngle-Ng Sign Bias — GJR base residuals (EDA §5b: expect null)")\n'
    'print("=" * 70)\n'
    'print(gjr_sb_df.to_string(index=False, float_format=\'{:.4f}\'.format))'
))

# 17d — Readiness summary
new_cells.append(md(
    '### Section 17d — Readiness Summary: GJR-GARCH-X\n\n'
    'All four GJR-X variants estimated and forecast. '
    'Full coefficient tables, Wald tests, model comparison, and narrative below.'
))

new_cells.append(code(
    'import glob\n'
    '\n'
    'print("=" * 72)\n'
    'print("READINESS SUMMARY — Section 17 (GJR-GARCH-X)")\n'
    'print("=" * 72)\n'
    '\n'
    '# ── 1. Artifacts ─────────────────────────────────────────────────────\n'
    'print("\\n[1] New GJR-X artifacts under outputs/")\n'
    'for fpath in sorted(glob.glob("outputs/gjr*") + glob.glob("outputs/forecasts_gjr*")):\n'
    '    size_kb = os.path.getsize(fpath) / 1024\n'
    '    print(f"    {os.path.basename(fpath):<52s} {size_kb:6.1f} KB")\n'
    '\n'
    '# ── 2. Full coefficient tables ────────────────────────────────────────\n'
    'print("\\n[2] GJR-X coefficient table — all specs and lags")\n'
    'SPEC_LAGS = [\n'
    '    (\'Main BIC\', gjrx_main_bic),\n'
    '    (\'Main L=1\', gjrx_main_l1),\n'
    '    (\'Aux  BIC\', gjrx_aux_bic),\n'
    '    (\'Aux  L=1\', gjrx_aux_l1),\n'
    ']\n'
    'for label, rdict_src in SPEC_LAGS:\n'
    '    print(f"\\n  --- {label} ---")\n'
    '    print(f"  {\'Metal\':<6} {\'d1\':>10} {\'t\':>7} {\'p\':>6}  "\n'
    '          f"{\'d2\':>10} {\'t\':>7} {\'p\':>6}  "\n'
    '          f"{\'xi\':>8} {\'WAsym-p\':>8} {\'WJoint-p\':>9}")\n'
    '    print("  " + "-" * 78)\n'
    '    for metal in METALS:\n'
    '        r = rdict_src.get(metal)\n'
    '        if r is None:\n'
    '            print(f"  {metal:<6} (no fit)")\n'
    '            continue\n'
    '        print(\n'
    '            f"  {metal:<6} {r[\'delta1\']:>10.4f}{sig_stars(r[\'d1_p\']):3s} "\n'
    '            f"{r[\'d1_t\']:>7.2f} {r[\'d1_p\']:>6.3f}  "\n'
    '            f"{r[\'delta2\']:>10.4f}{sig_stars(r[\'d2_p\']):3s} "\n'
    '            f"{r[\'d2_t\']:>7.2f} {r[\'d2_p\']:>6.3f}  "\n'
    '            f"{r[\'xi\']:>8.4f} {r[\'wald_asym_p\']:>8.4f} {r[\'wald_joint_p\']:>9.4f}"\n'
    '        )\n'
    '\n'
    '# ── 3. AIC/BIC comparison across all model families ──────────────────\n'
    'print("\\n[3] AIC/BIC comparison — GARCH(1,1) / EGARCH / GJR (base model AIC/BIC)")\n'
    'print(f"  {\'Metal\':<6} {\'GARCH11\':>10} {\'EGARCH\':>10} "\n'
    '      f"{\'GJR_main\':>10} {\'GJR_aux\':>10} "\n'
    '      f"{\'Best\':>12}")\n'
    'print("  " + "-" * 64)\n'
    'for metal in METALS:\n'
    '    g11_bic = garch11_results[metal].bic if metal in garch11_results else np.nan\n'
    '    eg_bic  = egarchx_results_bic[metal][\'bic\'] if metal in egarchx_results_bic and egarchx_results_bic[metal] else np.nan\n'
    '    gm_bic  = gjrx_main_bic[metal][\'bic\'] if metal in gjrx_main_bic and gjrx_main_bic[metal] else np.nan\n'
    '    ga_bic  = gjrx_aux_bic[metal][\'bic\']  if metal in gjrx_aux_bic  and gjrx_aux_bic[metal]  else np.nan\n'
    '    vals    = {\'GARCH11\': g11_bic, \'EGARCH\': eg_bic, \'GJR_main\': gm_bic, \'GJR_aux\': ga_bic}\n'
    '    best_k  = min(vals, key=lambda k: vals[k] if not np.isnan(vals[k]) else np.inf)\n'
    '    print(f"  {metal:<6} {g11_bic:>10.2f} {eg_bic:>10.2f} "\n'
    '          f"{gm_bic:>10.2f} {ga_bic:>10.2f} "\n'
    '          f"{best_k:>12}")\n'
    '\n'
    '# ── 4. Wald test summary ──────────────────────────────────────────────\n'
    'print("\\n[4] Wald test summary")\n'
    'print(f"  {\'Metal\':<6}  "\n'
    '      f"{\'MainBIC Wasym\':>14} {\'MainBIC Wjnt\':>13}  "\n'
    '      f"{\'AuxBIC Wasym\':>14}  {\'AuxBIC Wjnt\':>13}  "\n'
    '      f"{\'MainL1 Wasym\':>14}  {\'AuxL1 Wasym\':>13}")\n'
    'print("  " + "-" * 96)\n'
    'for metal in METALS:\n'
    '    rmb = gjrx_main_bic.get(metal)\n'
    '    rab = gjrx_aux_bic.get(metal)\n'
    '    rml = gjrx_main_l1.get(metal)\n'
    '    ral = gjrx_aux_l1.get(metal)\n'
    '    print(\n'
    '        f"  {metal:<6}  "\n'
    '        f"{(rmb[\'wald_asym_p\'] if rmb else np.nan):>14.4f} "\n'
    '        f"{(rmb[\'wald_joint_p\'] if rmb else np.nan):>13.4f}  "\n'
    '        f"{(rab[\'wald_asym_p\'] if rab else np.nan):>14.4f}  "\n'
    '        f"{(rab[\'wald_joint_p\'] if rab else np.nan):>13.4f}  "\n'
    '        f"{(rml[\'wald_asym_p\'] if rml else np.nan):>14.4f}  "\n'
    '        f"{(ral[\'wald_asym_p\'] if ral else np.nan):>13.4f}"\n'
    '    )\n'
    '\n'
    '# ── 5. Narrative ──────────────────────────────────────────────────────\n'
    'print("\\n[5] Narrative: asymmetry hypothesis and Tb highlight")\n'
    'print("-" * 72)\n'
    'for metal in METALS:\n'
    '    signals = []\n'
    '    rmb = gjrx_main_bic.get(metal)\n'
    '    rab = gjrx_aux_bic.get(metal)\n'
    '    rml = gjrx_main_l1.get(metal)\n'
    '    ral = gjrx_aux_l1.get(metal)\n'
    '\n'
    '    for label, r in [(\'main-BIC\', rmb), (\'aux-BIC\', rab), (\'main-L1\', rml), (\'aux-L1\', ral)]:\n'
    '        if r is None:\n'
    '            continue\n'
    '        if r[\'d1_p\'] < 0.10:\n'
    '            signals.append(f\'d1 sig @ {label} (p={r["d1_p"]:.3f})\')\n'
    '        if r[\'d2_p\'] < 0.10:\n'
    '            signals.append(f\'d2 sig @ {label} (p={r["d2_p"]:.3f})\')\n'
    '        if r[\'wald_asym_p\'] < 0.10:\n'
    '            dir_str = \'>delta1\' if (r[\'delta2\'] > r[\'delta1\']) else \'<delta1\'\n'
    '            signals.append(f\'Wasym sig @ {label} (delta2{dir_str}, p={r["wald_asym_p"]:.3f})\')\n'
    '        if r[\'wald_joint_p\'] < 0.10:\n'
    '            signals.append(f\'Wjoint sig @ {label} (p={r["wald_joint_p"]:.3f})\')\n'
    '\n'
    '    verdict = "Asymmetry evidence" if signals else "No signal"\n'
    '    summary = "; ".join(signals) if signals else "no delta significant across all specs"\n'
    '    print(f"  {metal} [{verdict}]: {summary}")\n'
    '\n'
    'print("\\n  Tb note: EDA §8 found NO Granger causality from tone or volume at lag 1.")\n'
    'print("  GJR-X corroborates if all Tb deltas are insignificant.")\n'
    '\n'
    'print("\\n" + "=" * 72)\n'
    'print("Section 17 complete. Sections 1-17 ready for evaluation prompt.")\n'
    'print("=" * 72)'
))

nb['cells'].extend(new_cells)

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Appended {len(new_cells)} cells (Sections 14-17) to Methodology.ipynb')
print(f'Total cells now: {len(nb["cells"])}')
